CQ00
edmcouncil/idmp pull request #213
Opened 2022-09-30 12:22 UTC by stsilva-osthus

wasn't sure what other folders to put this in so I left it at the top level

2022-10-19 12:48 UTC, Heiner-Oberkampf requested changes

2022-10-19 12:48 UTC, Heiner-Oberkampf commented on etc/CQ/cq0.sparql
> +FROM <https://spec.pistoiaalliance.org/idmp/ontology>
> I simply am checking these in for @Heiner-Oberkampf, I will remove the graphs since we do not have them in any of our other queries.

@mereolog @stsilva-osthus yes, you can remove the graph statements for the git version. Then I can approve

2022-11-24 10:45 UTC, Heiner-Oberkampf requested changes
@stsilva-osthus please remove the graph statement as described by Pawel if these are not used in the example data query execution.

2022-11-24 10:45 UTC, Heiner-Oberkampf commented on etc/CQ/cq0.sparql
> +FROM <https://spec.pistoiaalliance.org/idmp/ontology>
@stsilva-osthus please remove the graph statement as described by Pawel if these are not used in the example data query execution.

2022-11-28 15:16 UTC, mereolog approved these changes

2022-11-28 15:16 UTC, mereolog commented
@Heiner-Oberkampf could you re-review this so that I can merge it and close?

2022-12-09 07:56 UTC, merged