IDMP-298 - Rename IngredientRole to Ingredient, including its subclasses
edmcouncil/idmp pull request #223
Opened 2022-11-07 20:40 UTC by ElisaKendall

This resolution makes the following updates to the released, provisional, and informative ontologies:

1. Adds a distinct conformance level for name and annotations, including the definition, in contrast with naming conformance, which means that the concept has the same name as something in an ISO standard but not the same meaning.
2. Renames IngredientRole to Ingredient, including its subclasses ('active ingredient role' --> 'active ingredient', 'inactive ingredient role' --> 'inactive ingredient', 'adjuvant role' --> adjuvant, 'excipient role' --> excipient) and deprecates the original classes, making them equivalent to the new ones
3. Updates the examples that were impacted accordingly

2022-11-14 10:04 UTC, mereolog requested changes

2022-11-14 17:36 UTC, ElisaKendall commented on EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
>  	<owl:NamedIndividual rdf:about="&idmp-euctr;AluminumPhosphateAsActiveIngredientRole">
Done

2022-11-14 17:36 UTC, ElisaKendall commented on EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
>  	<owl:NamedIndividual rdf:about="&idmp-euctr;AluminumHydroxideAsActiveIngredientRole">
Done.

2022-11-15 15:20 UTC, mereolog approved these changes

2022-11-16 16:27 UTC, Heiner-Oberkampf approved these changes
was part of the discussion in Boston workshop

2022-11-16 16:28 UTC, merged