IDMP-312: Add SPOR Substances Transformation
edmcouncil/idmp pull request #238
Opened 2022-11-22 11:50 UTC by aliariff

@Heiner-Oberkampf @oleksandrsnizhko Please review

Signed-off-by: Ali Ariff <ali.ariff@accurids.com>

2022-11-28 07:58 UTC, oleksandrsnizhko approved these changes

2022-11-28 15:20 UTC, mereolog commented on etc/transformation/SPOR/substances/spor-substances.rqg
> +    cmns-txt:hasTextValue ?Substance_Name ;
This looks similar to https://github.com/edmcouncil/idmp/issues/239.

2022-12-07 07:39 UTC, Heiner-Oberkampf requested changes
minor improvement based on Pawels review

2022-12-07 07:39 UTC, Heiner-Oberkampf commented on etc/transformation/SPOR/substances/spor-substances.rqg
> +    cmns-txt:hasTextValue ?Substance_Name ;
@aliariff can you please use "https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/SubstanceName" instead of cmns-dsg:ContextualName

2022-12-07 13:38 UTC, mereolog approved these changes

2022-12-07 14:13 UTC, oleksandrsnizhko approved these changes

2022-12-07 14:32 UTC, merged