IDMP-366: Add RIM related IDMP concept: Packaged Medicinal Product
edmcouncil/idmp pull request #247
Opened 2022-12-04 23:04 UTC by ElisaKendall

Description: Added packaged medicinal product, including related concepts for container, package item, and other containers, as well as batch and batch identifier

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

2022-12-06 06:40 UTC, Heiner-Oberkampf submitted a review, later dismissed
Quick review. seems good

2022-12-06 15:03 UTC, mereolog requested changes

2022-12-06 16:22 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +
@merelog They are defined that way in the IDMP standards. In some cases the definition talks about a container that touches the pharmaceutical product (immediate container), in others the representation is for packaging that is in the "box" but doesn't touch the pharmaceutical product (intermediate container) and there is also outer packaging (the box). Of course, some drugs such as a bottle of tablets may not have all of these containers, but there are cases where all of them are present. And then there is this notion of a package item - which is the box or bottle itself, which is also manufactured.

2022-12-06 16:23 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +		<skos:definition>external container in which a Medicinal Product is supplied</skos:definition>
@merelog I didn't catch that one and fix it (copy/paste from the standard) - well spotted. I'll fix it.

2022-12-06 16:28 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +				<owl:onProperty rdf:resource="&cmns-col;comprises"/>
@mereolog I need to check the logic - contains is transitive and comprises is not, so I had to eliminate some min 0 restrictions as a consequence, which is why the allValuesFrom above is currently linked to owl:Thing. I might be able to change that to manufactured item but I need to walk the logic again to see what will happen if I do that.

2022-12-06 17:08 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +		<skos:definition>external container in which a Medicinal Product is supplied</skos:definition>
@mereolog Done.

2022-12-07 07:28 UTC, mereolog approved these changes

2022-12-07 07:29 UTC, merged

2022-12-07 07:30 UTC, Heiner-Oberkampf approved these changes

2022-12-07 07:30 UTC, Heiner-Oberkampf commented on EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
>  	<owl:NamedIndividual rdf:about="&idmp-euctr;GlaxoSmithKlineBiologicalsAsMarketingAuthorizationHolder">
These URIs are OK for specifying examples, but in general I would not see this in the IDMP Ontology itself for organizations as they are mastered in SPOR or LEI or some other registry - not by us.