IDMP-387 - Complete the set of terms required to answer UC-2, CQ-1
edmcouncil/idmp pull request #277
Opened 2022-12-30 05:03 UTC by ElisaKendall

Description: Extend the medicinal products ontology to include a number of bridge concepts required for UC-2, CQ-1, including process, process step, batch, lot, and a number of subordinate concepts and related identifiers. Note that this is likely incomplete, with more details required as the competency questions for this use case evolve, but it covers a number of existing gaps.

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

2022-12-30 08:36 UTC, mereolog requested changes

2022-12-30 08:36 UTC, mereolog commented on ISO/ISO11615-MedicinalProducts.rdf
> +			</owl:Restriction>
This looks odd: a certain designation comprises a time instant.
In FIBO we use [ExplicitDate](https://spec.edmcouncil.org/fibo/ontology/FND/DatesAndTimes/FinancialDates/ExplicitDate) to mark the temporal aspect of something by means of the dedicated sub-properties of [hasExplicitDate](https://spec.edmcouncil.org/fibo/ontology/FND/DatesAndTimes/FinancialDates/hasExplicitDate) and not via [comprises](https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/comprises). Moreover, the current textual definitions imply that if x comprises y, then x contains y, so some kind of parthood is involved. I cannot see how a time instant can be a part of a designation.
This remark applies to other such uses of comprise relation in this pull request.

2022-12-30 08:36 UTC, mereolog commented on ISO/ISO11615-MedicinalProducts.rdf
> +	</owl:Class>
Given its parent, the name ContinuousManufacturingProcess seems more adequate.

2022-12-30 08:36 UTC, mereolog commented on ISO/ISO11615-MedicinalProducts.rdf
> +	</owl:Class>
Given its parent, the name DiscreteManufacturingProcess seems more adequate.

2022-12-30 08:36 UTC, mereolog commented on ISO/ISO11615-MedicinalProducts.rdf
> +		<rdfs:range rdf:resource="&idmp-mprd;BatchProcess"/>
This looks wrong if we consider the usages of isBatchOf, e.g., https://github.com/edmcouncil/idmp/blob/92c954694783ac939ee6128ccaac238c5ddaac92/ISO/ISO11615-MedicinalProducts.rdf#L350-L354

2022-12-30 18:49 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +			</owl:Restriction>
@merelog In this case, the date is included as part of the designator according to the standard. In this case the date isn't only a temporal entity but is used as something like a qualifier to further differentiate the designation (since it may not be a unique identifier) from others.  It's providing additional context and is encoded in the designation. If you have other suggestions with that as background, I'd be happy to consider changing it.

2022-12-30 18:58 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +	</owl:Class>
@merelog While it is true that this is a subclass of manufacturing process, the terms continuous process, discrete process, and batch process are commonly used in industry. I've changed them as suggested and added the synonyms, but think we may get pushback on that from some stakeholders. I guess we'll have to see.

2022-12-30 18:59 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +	</owl:Class>
@merelog Done, but see above

2022-12-30 19:32 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +		<rdfs:range rdf:resource="&idmp-mprd;BatchProcess"/>
@merelog - I've simplified this by eliminating the new property and using isConstituentOf instead.

2023-01-02 07:43 UTC, mereolog commented on ISO/ISO11615-MedicinalProducts.rdf
> +			</owl:Restriction>
I would suggest introducing a distinction between dates as time instants, as they are now, and dates as strings/represenations of these time instants. This would require a substantial change to the whole ontology, so perhaps we should postpone it for now.

2023-01-02 07:44 UTC, mereolog approved these changes

2023-01-02 07:44 UTC, merged