IDMP-243 - stereochemisty
edmcouncil/idmp pull request #279
Opened 2023-01-05 15:16 UTC by tw-osthus

added definitions for 
cis, trans, absolute, achiral and mixed

mixed needs clarification with IDMP, the usage is not clear from the TS

2023-01-05 17:45 UTC, ElisaKendall submitted a review, later dismissed
This is fine with the updates made to correct hygiene related issues and move equivalences back to the deprecated classes they belong on, eliminate the default IRI Protege adds, etc.

2023-01-09 09:41 UTC, mereolog commented on ISO/ISO11238-Substances.rdf
> +		<cmns-av:explanatoryNote>despite containing two or more stereocenters the molecule is not chiral (achiral)</cmns-av:explanatoryNote>
Since this is a sentence, shouldn't the first letter of the first word be UPPERCASE?

2023-01-09 16:04 UTC, tw-osthus commented
I can do the merge, but I am concerned that I break things again on commit. I do not have this signing facility for example.

2023-01-09 17:05 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +		<cmns-av:explanatoryNote>until 1951 it was not possible to determine the absolute configuration and configuration were indicated relative to glyceraldehyde with the D/L system</cmns-av:explanatoryN
@merelog I'll fix this as well.

2023-01-10 17:58 UTC, ElisaKendall commented
> @tw-osthus could your resolve the conflicts that emerged?

@tw-osthus @mereolog I think this is done.

2023-01-11 06:49 UTC, Heiner-Oberkampf requested changes
Small wording correction needed and request to add axiom to make CIS and TRANS stereochemistries distinct.

2023-01-11 06:49 UTC, Heiner-Oberkampf commented on ISO/ISO11238-Substances.rdf
> +		<skos:definition>stereochemistry classifier indicating that the stereochemical description fully describes of the spatial arrangement of the atom of a chiral molecular entity (or group)</skos:defin
Grammar: should be ... "describes thespacial..." without "of"

2023-01-11 06:49 UTC, Heiner-Oberkampf commented on ISO/ISO11238-Substances.rdf
>  		<cmns-col:isMemberOf rdf:resource="&idmp-sub;ISO19844-CodeSet"/>
Based on the textual definition we could add an axiom that CIS and TRANS are different namedIndividuals analog to CHIRAL ACHIRAL example.

2023-01-11 07:22 UTC, mereolog submitted a review, later dismissed

2023-01-11 07:47 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
>  		<cmns-col:isMemberOf rdf:resource="&idmp-sub;ISO19844-CodeSet"/>
Done.

2023-01-11 07:48 UTC, ElisaKendall approved these changes
This addresses the recent feedback, is logically consistent, and passes hygiene.

2023-01-11 12:56 UTC, mereolog approved these changes

2023-01-11 17:01 UTC, Heiner-Oberkampf approved these changes

2023-01-11 17:01 UTC, merged