IDMP-371 - Add RIM related SPOR Referentials: Shelf Life Type and Special Precautions for Storage (WIP)
edmcouncil/idmp pull request #293
Opened 2023-01-20 04:30 UTC by ElisaKendall

Description: 
1. Augment the SPOR controlled vocabularies with a classifier for SPOR Shelf Life Type, including the individuals that can be used as examples for other such controlled vocabularies 
2. incorporate a property for the SPOR term status as some elements have a NULLIFIED status for Shelf Life rather than CURRENT

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

2023-01-20 06:49 UTC, Heiner-Oberkampf requested changes
I would like to discuss the target pattern as the agreed pattern should be reflected in the automated scripts. In particular the following aspects:
- creation of SPOR properties such as :hasSPORTermName, :hasPOROtherName, :hasSPORShortName :hasSPORDescription (why not use SKOS, or OMG patterns to keep things simple and more harmonized?)
- usage rdfs:label for the identifier in the named individuals
- usage of the Class name in the URI instead of the list code
- expression of record status and term status. could use the list
https://spor.ema.europa.eu/rmswi/#/lists/200000005003 instead of language tagged string
- usage of "cmns:isClassifiedBy" (more a understanding question as I would expect sth more like "classified as ... "
- examples for additional dates from SPOR (e.g., date modified etc)

2023-01-23 09:00 UTC, mereolog commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +		<idmp-spor:hasSPORTermStatus xml:lang="en">CURRENT</idmp-spor:hasSPORTermStatus>
Since SPOR term statuses are used quite often, I would recommend "reifying" them as individuals - this would require that idmp-spor:hasSPORTermStatus property be an object property.

2023-04-25 11:38 UTC, mereolog commented
@ElisaKendall where are with this? It looks old as the last comment is almost three months old.

2023-05-05 12:45 UTC, Heiner-Oberkampf requested changes
As discussed with Elisa we only need to add the following 2 classes to IDMP-O. The codes will come from the SPOR RMS lists

1. ShelfLifeType
2. SpecialPrecautionsforStorage

2023-07-13 06:17 UTC, mereolog approved these changes

2023-07-13 06:44 UTC, Heiner-Oberkampf approved these changes

2023-07-13 06:44 UTC, merged