IDMP-405 - Refactor the substance class hierarchy to differentiate actual physical substances from classifiers for substances (WIP)
edmcouncil/idmp pull request #303
Opened 2023-02-03 16:29 UTC by ElisaKendall

This resolution adds the concept of a substance classifier, and moves some of the subclasses that were originally subclasses of Substance to being subclasses of SubstanceClassifier accordingly. New properties that are defining properties for the classifiers have also been added.

2023-02-23 10:25 UTC, tw-osthus commented on CMNS/GovernmentEntities.rdf
> +		<cmns-av:adaptedFrom>Frascati Manual 2015 Guidelines for Collecting and Reporting Data on Research  and Experimental Development, https://www.oecd.org/sti/inno/Frascati-2015-Glossary.pdf</cmns-av:a
remove double blanks

2023-02-23 10:45 UTC, mereolog requested changes
One more comment - there is a difference between SubstanceComposition and ProductComposition with respect to the modelling of ingredient roles:
1. SubstanceComposition: hasRole some Ingredient
2. ProductComposition: hasIngredient some Ingredient.
Why is there a difference?

2023-02-23 15:46 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
>  	<owl:Class rdf:about="&idmp-sub;Substance">
yes substance and physical substances are disjoint

2023-02-23 15:48 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +			</owl:Restriction>
yes, a general substance can be specialized to a specific substance and both substances define a physical substance that exemplifies the specific substance

2023-02-23 15:50 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +		</owl:propertyChainAxiom>
I found this too. The class hierarchy would suggest "specifies". In the first version it was "classifies" because substances were classifiers and what we have is "defines".

2023-02-23 16:16 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +				<owl:onProperty rdf:resource="&cmns-col;isDefinedIn"/>
cmns-cls:characterizes/isCharacterizedBy is also a candidate which I have used in my local branch

2023-02-23 16:55 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +			</owl:Restriction>
The moiety topic is difficult, and I suggest we table it for now.

The IDMP definition states it is an entity within a substance that has a complete and continuous molecular structure. This makes it difficult to define it correctly.  To me only molecules have a molecular structure and if we state that a physical substance has a molecular structure, then we mean that the collective of molecules that form the physical substance share a common molecular structure (are the same kind of molecules).
So I would say no, a physical substance has no moiety as part.

IUPAC  defines moiety only on the molecular level https://goldbook.iupac.org/terms/view/M03968;
In physical organic chemistry moiety is generally used to signify part of a molecule, e.g. in an ester R1COOR2 the alcohol moiety is R2O. The term should not be used for a small fragment of a molecule.

so a moiety is a molecular entity.
so physical substance defined in Amlodipine Besylate is composed of at molecular level Amlodipine Besylate molecule that has moeity -> Amlodipine molecule

This is not compliant with the definition that moiety is a part of a substance, but substances being specifications, do not have parts in this sense.

As shortcuts I would define for chemical substance
chemical substance hasDefinedMolecularEntity molecular entity.
and has moeity can be a sub property of that..

2023-02-23 16:56 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +			</owl:Restriction>
by the way physical substance is disjoint with molecular entity

2023-02-24 10:33 UTC, tw-osthus commented on EXT/Examples/AmlodipineExample.rdf
>  		<cmns-dsg:defines rdf:resource="&idmp-amp;AmlodipineEMC"/>
ingredient and constiuency needs more rework.

AmlodipineEMCConstituency is a specified constituency. It defines the constituency of  any AmlodipineEMC physical substances or physical pharmaceutical products.

AmlodipineMesylateMonohydrateAsActiveIngredientInAmlodipineEMC is an active ingredient specification, sub class of ingredient specification.
AmlodipineEMCConstituency has not an active ingredient, it specifies an active ingredient.

An (active) ingredient is manifested in physical matter,


In a pharmaceutical product (spec) the ingredient is part of the criteria that specify the physical pharmaceutical product that target the constituency of the product. It specifies the substance and its concentration/relative amount.

In a recipe to produce the product the ingredient is the specified starting material in that process.

They are role specifications. It specifies the role of the specified physical substance in the physical pharmaceutical product or the actual production process instance.  The substance specification does not change when the substance is used as an ingredient. 
for example:
The tablet is made of AmlodipineTabletSubstance  which is a defined mixture of Amlodipine and other substances, and of a coating. The relative amount of physical Amlodipine per tablet is specified in the ingredient role which has as reference a single tablet. For the AmlodipineTabletSubstance mixture there can be also an ingredient role of Amlodipine. It would specify the concentration of Amlodipine in the mixture, e.g. 10 mg Amlodipine per g AmlodipineTabletSubstance or 1%. If we produce a tablet with this mixture, the Amlodipine concentration per 1 g tablet would be a bit less then 10 mg/tablet (the coating does not contain Amlodipine).

2023-02-25 22:51 UTC, ElisaKendall commented on CMNS/GovernmentEntities.rdf
> +		<cmns-av:adaptedFrom>Frascati Manual 2015 Guidelines for Collecting and Reporting Data on Research  and Experimental Development, https://www.oecd.org/sti/inno/Frascati-2015-Glossary.pdf</cmns-av:a
Nice catch - done.

> 

I was focused on product composition, where the ingredient role is clearly the parent. I've fixed this. Note that substances can play roles in a product that may not always be ingredients - such as solvents that are used in the manufacturing process, so we don't want to limit the role a substance can play in a product to solely that of an ingredient.

2023-02-25 22:52 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +			</owl:Restriction>
> One more comment - there is a difference between SubstanceComposition and ProductComposition with respect to the modelling of ingredient roles:
> 
> 1. SubstanceComposition: hasRole some Ingredient
> 2. ProductComposition: hasIngredient some Ingredient.
>    Why is there a difference?

I was focused on product composition, where the ingredient role is clearly the parent. I've fixed this. Note that substances can play roles in a product that may not always be ingredients - such as solvents that are used in the manufacturing process, so we don't want to limit the role a substance can play in a product to solely that of an ingredient.

2023-02-25 23:20 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
>  	<owl:Class rdf:about="&idmp-sub;Substance">
done.

2023-02-25 23:21 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +	<owl:Class rdf:about="&idmp-sub;PhysicalSubstance">
done.

2023-02-25 23:21 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
>  	<owl:Class rdf:about="&idmp-sub;Substance">
done.

2023-02-25 23:22 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
>  	<owl:Class rdf:about="&idmp-sub;Substance">
done.

2023-02-25 23:27 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +			</owl:Restriction>
@tw-osthus I think these are valuable additions, Thomas, but I agree that we should add them carefully in another update. I can just imagine some of the Monday discussions around this ... before we achieve agreement, and would like to get this initial pass done first.

2023-02-25 23:34 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
>  	</owl:ObjectProperty>
@merelog This is fair - we made the distinction between contains as a specification and container as a thing, but immediately contains is related to the specifications. I have changed that to definitionallyImmediatelyContains to be clearer.

2023-02-26 00:03 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +		</owl:propertyChainAxiom>
@merelog, @tw-osthus Ok - I've moved 'specifies' which wasn't used anywhere yet, to the documents ontology where we added specification, and replaced 'defines' with specifies, and added more property chain axioms as well. But specifies shouldn't replace defines in all cases - not for compositions, for example, so I didn't change all occurrences.

2023-02-26 21:30 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +			</owl:Restriction>
> This may be misleading given that the domain of `idmp-sub:isStoichiometric` is `idmp-sub:ChemicalSubstance`. The restriction implies that an instance of `idmp-sub:PhysicalSubstance` may have `idmp-sub:isStoichiometric` property, but if it does have it, then it becomes an instance of `idmp-sub:ChemicalSubstance` as well.

Removed the restriction from physical substance, since it is specified by substance.

2023-02-26 22:13 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> -		<rdfs:range rdf:resource="&idmp-sub;Substance"/>
@tw-osthus I've eliminated the unions and restricted isRelatedSubstanceTo back to substances and not physical substances. We will have to see over time whether or not this turns out to be an issue, though I understand the concern.

2023-02-26 22:21 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
>  	<owl:Class rdf:about="&idmp-sub;Ingredient">
@Pawel - to be an ingredient, which is a role it must be manifested in 'something' - due to the notes we have from SMEs, a given ingredient in some quantity can only be used in at most one pharmaceutical product. a PharmaceuticalProduct is typically a manufactured item. I would like to confirm with SMEs that if an ingredient is used in a manufactured item which isn't a pharmaceutical product then it can be used exactly one time. Then we could change the someValues restriction to exactly 1, but that's not clear from the specification.

2023-02-26 22:22 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +				<owl:onProperty rdf:resource="&cmns-col;isDefinedIn"/>
@tw-osthus I've made the change for defines/isDefinedIn to specifies/isSpecifiedBy where appropriate, but haven't renamed the defining properties yet, which I think are ok.

2023-02-26 22:23 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +	<owl:ObjectProperty rdf:about="&idmp-sub;hasOpticalActivity">
@tw-osthus We have both now, with the defining one being part of a property chain.  I think this is done.

2023-02-26 22:25 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +		<rdfs:domain>
@tw-osthus I think it is imprecise in both cases based on the pharma use cases we have. We can ask in the Monday call though.

2023-02-26 22:26 UTC, ElisaKendall commented on EXT/Examples/AmlodipineExample.rdf
>  		<cmns-dsg:defines rdf:resource="&idmp-amp;AmlodipineEMC"/>
@tw-osthus I agree that the examples need clarification - that work will be done under other issues once the main one has been integrated.

2023-02-26 22:27 UTC, ElisaKendall commented
> One more comment - there is a difference between SubstanceComposition and ProductComposition with respect to the modelling of ingredient roles:
> 
> 1. SubstanceComposition: hasRole some Ingredient
> 2. ProductComposition: hasIngredient some Ingredient.
>    Why is there a difference?

This is related to the moiety question - a substance can have moieties, and these are not necessarily ingredients per se - we have another subproperty of hasRole for this - whereas products are always composed of ingredients.

2023-02-27 08:00 UTC, mereolog requested changes
https://spec.pistoiaalliance.org/idmp/ontology/AboutIDMPDev-ReferenceIndividuals/ is inconsistent.

```
ERROR  08:58:55  An error occurred during reasoning: Cannot do reasoning with inconsistent ontologies!
Reason for inconsistency: Individual https://gsrs.ncats.nih.gov/api/v1/substances/1J444QC288 is forced to belong to class https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Substance and its complement.
```

2023-02-27 08:01 UTC, mereolog commented
Also there is quite a few complaints from Protege like this one:
`ERROR  08:57:28  Attempt to transform an axiom to correct misuse of properties failed. Property replacement: {hasMolecularFormula=hasMolecularFormula, hasMolecularFormulaByMoiety=hasMolecularFormulaByMoiety}, axiom: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine> hasMolecularFormula "C20H25ClN2O5", error: class uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression cannot be cast to class org.semanticweb.owlapi.model.IRI (uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression and org.semanticweb.owlapi.model.IRI are in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @3150329b)`

2023-02-27 17:34 UTC, ElisaKendall commented
> https://spec.pistoiaalliance.org/idmp/ontology/AboutIDMPDev-ReferenceIndividuals/ is inconsistent.
> 
> ```
> ERROR  08:58:55  An error occurred during reasoning: Cannot do reasoning with inconsistent ontologies!
> Reason for inconsistency: Individual https://gsrs.ncats.nih.gov/api/v1/substances/1J444QC288 is forced to belong to class https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Substance and its complement.
> ```

This is due to not updating the examples in this issue. I will make those changes here but then will close the other two Jira issues regarding the examples to the resolution of this issue,.

2023-02-27 18:28 UTC, ElisaKendall commented
> Also there is quite a few complaints from Protege like this one: `ERROR 08:57:28 Attempt to transform an axiom to correct misuse of properties failed. Property replacement: {hasMolecularFormula=hasMolecularFormula, hasMolecularFormulaByMoiety=hasMolecularFormulaByMoiety}, axiom: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine> hasMolecularFormula "C20H25ClN2O5", error: class uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression cannot be cast to class org.semanticweb.owlapi.model.IRI (uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression and org.semanticweb.owlapi.model.IRI are in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @3150329b)`

These have been fixed.

2023-02-27 18:28 UTC, ElisaKendall commented
> https://spec.pistoiaalliance.org/idmp/ontology/AboutIDMPDev-ReferenceIndividuals/ is inconsistent.
> 
> ```
> ERROR  08:58:55  An error occurred during reasoning: Cannot do reasoning with inconsistent ontologies!
> Reason for inconsistency: Individual https://gsrs.ncats.nih.gov/api/v1/substances/1J444QC288 is forced to belong to class https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Substance and its complement.
> ```

Fixed / done.

2023-02-28 08:16 UTC, mereolog approved these changes

2023-02-28 12:58 UTC, tw-osthus approved these changes

2023-02-28 13:22 UTC, merged