GitHub action for competency questions run as unit tests
edmcouncil/idmp pull request #304
Opened 2023-02-06 10:07 UTC by mereolog

2023-02-17 13:21 UTC, tw-osthus commented
This is ok, however I find it difficult to use JSON for the expected data instead of CSV. The JSON result returned from the SPARQL query is very verbose and hard to write. This is esp. a barrier for SMEs.

2023-02-17 13:40 UTC, mereolog commented
> > This is ok, however I find it difficult to use JSON for the expected data instead of CSV. The JSON result returned from the SPARQL query is very verbose and hard to write. This is esp. a barrier for SMEs.
> 
> What is the expectation there? I mean for example when I build an application's backend to work with for the front end I usually do not care about the expected results of a unit test, only that the unit test passes. In other words, should SMEs be looking at the unit tests themselves or just whether or not they pass/fail?

I did not intend SMEs to verify the expected/actual results from the query - in my view they should look at whether a test passed or failed.

But I appreciate @tw-osthus concern about readability and will wait for others' views on that.

2023-02-21 14:18 UTC, oleksandrsnizhko requested changes

2023-02-21 14:18 UTC, oleksandrsnizhko commented on .github/workflows/unit_tests_run.yml
> +        sudo chmod +x /usr/bin/robot
I guess that the `sudo` commands used to install `robot` should not be necessary, as the actions/setup-python step already sets up a virtual environment where pip packages can be installed without elevated privileges.

2023-02-21 14:18 UTC, oleksandrsnizhko commented on etc/CQ/Example/cq1.sparql
> +	#BIND("amlodipine" AS ?activeMoietyLabel )
Would you like to keep this comment here? If yes, it would make sense to make it consistent and add a comment to the cq0.sparql file

2023-02-21 14:18 UTC, oleksandrsnizhko commented on etc/unit_tests/unit_test_runner.py
> +        file.close()
We could remove unnecessary `file.close()` statements since `with` statements automatically close files.

2023-02-21 14:18 UTC, oleksandrsnizhko commented on etc/unit_tests/unit_test_runner.py
> +        file.close()
We could remove unnecessary `file.close()` statements since `with` statements automatically close files.

2023-02-21 14:18 UTC, oleksandrsnizhko commented on etc/unit_tests/unit_test_runner.py
> +    return sparql_query
In the `get_sparql_query` function, the for-loop that replaces the parameters in the query is iterating over the keys of the config['parameters'] dictionary, which might not preserve the order of parameters. So, it's recommended to iterate over the `sparql_parameters` list directly to maintain the parameter order.

```
def get_sparql_query(config: dict, root_folder: str) -> str:
    with open(os.path.join(root_folder, config['sparql_template'])) as file:
        sparql_template = file.read()
    sparql_parameters = config['parameters']
    sparql_query = sparql_template
    for sparql_parameter in sparql_parameters:
        sparql_query = sparql_query.replace(sparql_parameter, '"' + sparql_parameters[sparql_parameter] + '"')
    return sparql_query
```

2023-02-21 15:12 UTC, mereolog commented on etc/CQ/Example/cq1.sparql
> +	#BIND("amlodipine" AS ?activeMoietyLabel )
Comment removed.

2023-02-21 15:12 UTC, mereolog commented on etc/unit_tests/unit_test_runner.py
> +        file.close()
Statement removed.

2023-02-21 15:12 UTC, mereolog commented on etc/unit_tests/unit_test_runner.py
> +    return sparql_query
Changed as requested.

2023-02-21 15:12 UTC, mereolog commented on etc/unit_tests/unit_test_runner.py
> +        file.close()
Statement removed.

2023-02-21 15:14 UTC, mereolog commented on .github/workflows/unit_tests_run.yml
> +        sudo chmod +x /usr/bin/robot
Unfortunately, without sudo commands GitHub keeps throwing me error like:
2023-02-21T15:06:07.4685371Z /usr/bin/robot: Permission denied
2023-02-21T15:06:07.4688543Z Cannot write to ‘/usr/bin/robot’
So I think they need to stay there.

2023-02-21 15:15 UTC, oleksandrsnizhko approved these changes

2023-02-21 15:15 UTC, aliariff commented on .github/workflows/unit_tests_run.yml
> +        python -m pip install rdflib
It will make sense to create `requirements.txt` here and put all the dependencies with the exact version.
and then we can just `pip install -r requirements.txt`

2023-02-21 15:31 UTC, mereolog commented on .github/workflows/unit_tests_run.yml
> +        python -m pip install rdflib
Done, I think.

2023-02-21 15:38 UTC, oleksandrsnizhko approved these changes

2023-02-21 15:58 UTC, aliariff commented on etc/unit_tests/requirements.txt
> +rdflib
Can we set a specific version for it? This is to avoid issues when in the future there is a breaking change from the libraries

2023-02-21 15:58 UTC, aliariff commented on .github/workflows/unit_tests_run.yml
> +        pip install -r /home/runner/work/idmp/idmp/etc/unit_tests/requirements.txt
Doesn't work with relative path? eg: `./etc/unit_tests/requirements.txt`

2023-02-21 16:12 UTC, mereolog commented on etc/unit_tests/requirements.txt
> +rdflib
Done.

2023-02-21 16:12 UTC, mereolog commented on .github/workflows/unit_tests_run.yml
> +        pip install -r /home/runner/work/idmp/idmp/etc/unit_tests/requirements.txt
Changed to the relative path.

2023-02-21 16:15 UTC, aliariff approved these changes
LGTM

2023-02-21 16:17 UTC, oleksandrsnizhko approved these changes

2023-02-22 16:12 UTC, merged