IDMP-528 - The definition of physical substance in the ISO 11238 ontology should correspond to the precise wording from paragraph 3.84
edmcouncil/idmp pull request #351
Opened 2023-05-01 20:29 UTC by ElisaKendall

Description: Revised the substances definitions of physical manufactured item and physical substance to reflect the precise wording from ISO 11238

Signed-off-by: Elisa Kendall [ekendall@thematix.com](mailto:ekendall@thematix.com)

2023-05-02 08:43 UTC, tw-osthus requested changes

2023-05-02 08:43 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +		<skos:definition>qualitative and quantitative composition of a product as contained in the packaging of the medicinal product</skos:definition>
This is the definition for the specification of the manufactured item. It is wrong or at least very misleading as definition of the physical manufactured item. Note that we have the product constituency which would better fit this definition.

2023-05-02 14:15 UTC, ElisaKendall commented
@tw-osthus Amgen specifically requested that we change the definition for this element to the language from the specification though. So if the definition was more appropriate as we had it, we will need to explain fully to Amgen.

2023-05-02 14:47 UTC, tw-osthus commented
Amgen needs to understand the difference between the physical manufactured item and the manufactured item. The physical manufactured item is only an interface for an IDMP specification to the inventory or a specific case or study, where the physical MI is used. Changing the definition to something, that does not match the formal definitions (class hierarchy and restrictions) is an error that must be fixed.

The PMI is a product, and it embodies a composition, but it is not a composition. That would be a dependent quality/characteristic of the independent physical thing, that is packaged innermost in the PMP, so the definition is wrong.

2023-05-03 00:50 UTC, ElisaKendall commented
@tw-osthus After discussion with Heiner earlier today, we agreed that the original definition was fine and ensured that there is an annotation stating that physical manufactured item is specifically an extension to the standard. This way we can defend the fact that the definition isn't identical to the original.

2023-05-03 08:07 UTC, tw-osthus submitted a review, later dismissed

2023-05-03 18:04 UTC, tw-osthus approved these changes

2023-05-03 18:34 UTC, merged