Update uc2_cq1b.sparql
edmcouncil/idmp pull request #362
Opened 2023-05-04 09:03 UTC by dharmen-punjani

Simplifying query using property path for PharmaceuticalProduct with multilevel of packaging.

2023-05-09 07:18 UTC, mereolog requested changes

2023-05-09 07:18 UTC, mereolog commented on etc/CQ/Example/uc2_cq1b.sparql
> +} GROUP BY $StockKeepingUnit
`} GROUP BY $StockKeepingUnit`
should read
`} GROUP BY ?StockKeepingUnit`

2023-05-09 07:18 UTC, mereolog commented on etc/CQ/Example/uc2_cq1b.sparql
>  		# Optionally, get the name of the substance
Shouldn't
`# Optionally, get the name of the substance`
read
`# Optionally, get the name of the stock keeping unit`?

2023-05-09 07:18 UTC, mereolog commented on etc/CQ/Example/uc2_cq1b.sparql
>  		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }
That these triples are optional looks odd given that `?StockKeepingUnitLabel` is used in the result set:
`SELECT DISTINCT ?StockKeepingUnit (SAMPLE(?StockKeepingUnitLabel) AS ?StockKeepingUnitName)`

2023-08-03 13:35 UTC, mereolog commented
@dharmen-punjani what shall we do with this pull-request?
It is rather old by now - shall I close it?

2023-08-09 13:44 UTC, dharmen-punjani commented
@mereolog  I think this can be merged as the pattern is not changed and this gives same results as the current one. 
@tw-osthus and @stsilva-osthus can you review this?

2023-08-18 18:13 UTC, mereolog commented
@dharmen-punjani could you resolve the merge conflict first?

2023-08-23 15:00 UTC, dharmen-punjani commented
@mereolog done.

2023-09-15 14:16 UTC, mereolog approved these changes
If the result set below is correct, this pr can be merged in.

StockKeepingUnit | StockKeepingUnitName
-- | --
https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/P015011211 | P015011211

2023-09-22 08:09 UTC, tw-osthus commented on etc/CQ/Example/uc2_cq1b.sparql
>  		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }
SKUs should use cmns-txt:hasTextValue for the code not rdfs:label. The rdf:label is only used for the hygiene test 😉

but regarding optional, the SKU might be optional, but the code of the SKU is not. A SKU without code is useless, if the code is not otherwise encoded as part of the IRI. Identifiers should not have IRIs on their own IMHO and should be blank nodes, but this is a different topic.

2023-09-22 08:11 UTC, tw-osthus requested changes

2023-09-22 08:11 UTC, tw-osthus commented on etc/CQ/Example/uc2_cq1b.sparql
> -		OPTIONAL{?StockKeepingUnit  rdfs:label  ?StockKeepingUnitLabel }
cmns-txt:hasTextValue

2023-09-25 05:28 UTC, mereolog commented
@dharmen-punjani also could you resolve the merge conflict?

2023-12-14 15:52 UTC, ElisaKendall commented
@dharmen-punjani - I had to fix the query for the latest revisions to the ontology. I think this would need to be re-compared with the current working query again, as it's isn't the same and there are likely additional conflicts.  Would you please take a look?

2023-12-18 11:25 UTC, mereolog commented
@dharmen-punjani could you resolve the merge conflict?

2023-12-18 11:26 UTC, mereolog requested changes
See https://github.com/edmcouncil/idmp/pull/362#issuecomment-1860211446.

2024-01-03 16:29 UTC, dharmen-punjani commented
@ElisaKendall  Updated the query as per the changes in ontology.
@mereolog  resolved conflict

2024-01-25 14:45 UTC, mereolog commented
I am closing this due to the lack of activity.

2024-01-25 14:45 UTC, closed without merging