update config file
edmcouncil/idmp pull request #398
Opened 2023-06-27 13:25 UTC by patrycjamia

update config file

2023-07-03 10:10 UTC, mereolog requested changes

2023-07-04 05:35 UTC, mereolog approved these changes

2023-07-05 17:52 UTC, ElisaKendall approved these changes

2023-07-05 17:53 UTC, ElisaKendall commented
@mereolog I've approved this but there is a conflict that needs to be addressed

2023-07-07 14:37 UTC, mereolog approved these changes

2023-07-07 14:37 UTC, merged