IDMP-533 - Provide alignment/mapping for ISO "codedConcept" to the target IDMP-O Pattern for Reference Code Lists (WIP)
edmcouncil/idmp pull request #426
Opened 2023-07-21 14:47 UTC by ElisaKendall

Description: 

1. Add the OMG formal standard ontologies for Multiple Vocabulary Facility to the iDMP GitHub for use as needed for representation of controlled vocabularies

2023-07-27 01:42 UTC, avilesg submitted a review, later dismissed
There's a lot of good work here.  Looking forward to the examples and supporting documentation to share the patterns internally.

2023-07-27 08:29 UTC, mereolog requested changes

2023-07-27 08:29 UTC, mereolog commented on MVF/AboutMVF.rdf
> +		<owl:imports rdf:resource="https://www.omg.org/spec/MVF/ISO1087-TerminologyScience/"/>
Why is https://www.omg.org/spec/MVF/MVFtoSKOSMapping/ not imported here?

2023-07-27 08:29 UTC, mereolog commented on AboutIDMPDev.rdf
> +
Why are 
- https://www.omg.org/spec/MVF/MVFtoSKOSMapping/
- https://www.omg.org/spec/MVF/ISO1087-TerminologyScience/
not imported here?

2023-07-27 08:29 UTC, mereolog commented on MVF/ISO1087-TerminologyScience.rdf
> +		<rdfs:label>term harmonization</rdfs:label>
term formation

2023-07-27 15:05 UTC, ElisaKendall commented on MVF/MetadataMVF.rdf
> +		<owl:versionIRI rdf:resource="https://www.omg.org/spec/MVF/MetadataMVF/spec.pistoiaalliance.org/idmp/ontology/MVF/20230701/MetadataMVF/"/>
@merelog good catch - I hadn't noticed that as I'm sure you guessed

2023-07-27 15:17 UTC, ElisaKendall commented on MVF/AboutMVF.rdf
> +<rdf:RDF
@mereolog This about file is the OMG version - I'll raise the issue there in the task force. We don't really need it for IDMP, it's only for convenience.

2023-07-27 15:19 UTC, ElisaKendall commented on MVF/AboutMVF.rdf
> +		<owl:imports rdf:resource="https://www.omg.org/spec/MVF/ISO1087-TerminologyScience/"/>
@merelog - we didn't want to force importing SKOS, depending on who is using this. The mapping was provided at OMG for convenience. The about file is a metadata / convenience file we use to load all of the ontologies, but isn't normative.

2023-07-27 15:36 UTC, ElisaKendall commented on AboutIDMPDev.rdf
> +
@merelog - see above - we don't need them currently for IDMP, so I didn't bring them in.

2023-07-27 16:17 UTC, Heiner-Oberkampf approved these changes

2023-07-28 06:10 UTC, mereolog commented on AboutIDMPDev-ReferenceIndividuals.rdf
> +
> @mereolog - we don't need them for IDMP - I've only loaded the ones we need at this point.

Then these two are not run through the hygiene tests - the scope of the hygiene test is defined by the "import" statements of [AboutIDMPDev-ReferenceIndividuals.rdf](https://github.com/edmcouncil/idmp/pull/426/files/c4e7824936e9e77faa58743a9d9267cbbde05b2b#diff-69a4e87818b81f673bf69a515889354f19575e4cdcbd2dac7fc777b78e2204fa).

2023-07-28 06:12 UTC, mereolog commented on MVF/AboutMVF.rdf
> +		<owl:imports rdf:resource="https://www.omg.org/spec/MVF/ISO1087-TerminologyScience/"/>
> @merelog - we didn't want to force importing SKOS, depending on who is using this. The mapping was provided at OMG for convenience. The about file is a metadata / convenience file we use to load all of the ontologies, but isn't normative.

This introduces the difference between [MVF/AboutMVF.rdf](https://github.com/edmcouncil/idmp/pull/426/files/c4e7824936e9e77faa58743a9d9267cbbde05b2b#diff-d68d3e6f07bb22e43bbd96f56688dbe237968b7e919de4fdc466d6182f2d7b57) and [AboutIDMPDev-ReferenceIndividuals.rdf](https://github.com/edmcouncil/idmp/pull/426/files/c4e7824936e9e77faa58743a9d9267cbbde05b2b#diff-69a4e87818b81f673bf69a515889354f19575e4cdcbd2dac7fc777b78e2204fa) - the former has one more import than the latter:
`owl:imports rdf:resource="https://www.omg.org/spec/MVF/ISO1087-TerminologyScience/`
Is there a reason for this difference?

2023-07-28 06:25 UTC, ElisaKendall commented on MVF/AboutMVF.rdf
> +		<owl:imports rdf:resource="https://www.omg.org/spec/MVF/ISO1087-TerminologyScience/"/>
@mereolog We don't need that one either, and I'm still debating about the ISO 1087 terms and definitions one, but I think I want to use that one for coded concepts which are an extension of the notion of a concept descriptor in IDMP ... stay tuned though - it may be overkill. I can always remove it from the load files in a subsequent update, but don't want to make that decision until I finish an example .... in a new issue / pull request

2023-07-28 06:27 UTC, ElisaKendall commented on AboutIDMPDev-ReferenceIndividuals.rdf
> +
@mereolog That works for me - if we don't need them, I don't want to import them for IDMP. I can't change the OMG about file here without raising the issue on the OMG side, and the ontologies are part of that standard, thus the difference between what we are importing for IDMP and what is imported for the entire standard on the OMG side.

2023-07-28 06:35 UTC, merged