IDMP-618 Augment Example Data for UC3 CQ 3
edmcouncil/idmp pull request #430
Opened 2023-07-24 13:47 UTC by tw-osthus

Description:
add oral use as route of administration for Norvask pharmaceutical product (Amlodipine example)
add intravenous use as route of adminstration for Terlipressin pharmaceutical product
add terms reference to SPOR RMS

2023-07-24 16:53 UTC, ElisaKendall approved these changes

2023-07-25 05:38 UTC, Heiner-Oberkampf requested changes
Example should use SPOR reference instead of creating new definitions for ROA oral use etc.

2023-07-25 05:38 UTC, Heiner-Oberkampf commented on EXT/Examples/AmlodipineExample.rdf
> +		<rdfs:label>Oral use</rdfs:label>
The concept is available in SPOR and in EDQM for reference. It may need update to Elisas pattern for controlled vocabularies but I would not repeat the referenced concept for "oral use" here.
See SPOR: https://pistoiaalliance.accurids.com/details/aHR0cHM6Ly9zcG9yLmVtYS5ldXJvcGEuZXUvcm1zd2kvIy9saXN0cy8xMDAwMDAwNzMzNDUvdGVybXMvMTAwMDAwMDczNjE5
See EDQM: https://pistoiaalliance.accurids.com/details/aHR0cHM6Ly9kYXRhLnBpc3RvaWFhbGxpYW5jZS5vcmcvaWRtcC9lZHFtL1JPQS0yMDA1MzAwMA

2023-07-25 05:38 UTC, Heiner-Oberkampf commented on EXT/Examples/TerlipressinExample.rdf
> +		<skos:definition>Injection of a medicinal product into a vein.</skos:definition>
same here. no need to add a new definition but rather reference SPOR or EDQM

2023-07-25 06:53 UTC, tw-osthus commented on EXT/Examples/AmlodipineExample.rdf
> +		<rdfs:label>Oral use</rdfs:label>
This is the SPOR reference: <rdf:type rdf:resource="&idmp-eura;**SPOR**-ReferentialsManagementSystemTerm"/>

2023-07-26 15:20 UTC, Heiner-Oberkampf approved these changes

2023-07-26 15:26 UTC, merged