IDMP-619 add UC3 CQ3
edmcouncil/idmp pull request #433
Opened 2023-07-25 09:56 UTC by tw-osthus

2023-07-27 13:45 UTC, mereolog commented on etc/unit_tests/configs/idmp_tests_config.yaml
> +    uc3_cq2_parameter_1: "100000073619"
uc3_cq2_parameter_1 > uc3_cq3_parameter_1

2023-08-10 13:59 UTC, avilesg approved these changes

2023-08-10 14:06 UTC, mereolog requested changes
See https://github.com/edmcouncil/idmp/pull/433#discussion_r1276305679.

2023-08-21 13:37 UTC, mereolog requested changes
Some more work on this pull-request is needed because currently uc3_cq3_tests returns an empty result set.

2023-08-21 18:00 UTC, tw-osthus commented
It is very strange, because locally the SPARQL runs fine.

2023-08-22 07:21 UTC, mereolog commented
> It is very strange, because locally the SPARQL runs fine.

I got the same result, i.e., the empty result set, in [data.world](https://data.world/edm-council/idmp-ontology/workspace/query?queryid=cb8a3518-db03-4c48-92f5-d8267bb12731).

2023-08-22 09:42 UTC, tw-osthus commented
Fuseki keeps the old dataset on the disk, even when it has been deleted in the UI. If you re-create it with the same name, it still uses the old version! This was the reason, why I still got results with cmns-pts:isPlayedBy.

2023-09-13 20:13 UTC, merged