Some missing unit tests added
edmcouncil/idmp pull request #444
Opened 2023-08-07 12:22 UTC by mereolog

This adds missing unit types for those queries that return non-empty results.

Note that the following queries return empty results for amlodipine:
- uc1_cq8
Note that the following queries return empty results for terlipressin:
- uc2_cq1b
- uc2_cq1d
- uc2_cq2-1

2023-08-08 15:33 UTC, ElisaKendall approved these changes

2023-08-09 13:50 UTC, dharmen-punjani commented on etc/unit_tests/configs/idmp_tests_config.yaml
Here the parameters are for Amlodipine. Should it be for Terlipressin as it says uc1_cq6_test_**terlipressin** ?

2023-08-09 13:52 UTC, dharmen-punjani requested changes
values under uc1_cq6_tests_terlipressin should be updated to terlipressin parameter there are parameter for amlodipine at the moment.

2023-08-10 07:27 UTC, mereolog commented
> values under uc1_cq6_tests_terlipressin should be updated to terlipressin parameter there are parameter for amlodipine at the moment.

Done.

2023-08-10 08:26 UTC, dharmen-punjani approved these changes

2023-08-10 08:27 UTC, merged