IDMP-533a - Provide alignment/mapping for ISO "codedConcept" to the target IDMP-O Pattern for Reference Code Lists
edmcouncil/idmp pull request #448
Opened 2023-08-10 05:32 UTC by ElisaKendall

Description: extended the definitions included in the SPOR RMS EU ontology to better represent example controlled vocabularies and terms per the latest patterns

2023-08-10 09:02 UTC, tw-osthus requested changes
the SubstancesProductsOrganisationsReferential.rdf ontology needs legal review.

I have access to SPOR and the license for the SPOR list for shelf life type:
_1.8.  Copyright and other disclaimers
The content of this list and associated intellectual property rights were developed under projects funded by the EMA therefore becoming the property of the EMA.
Reproduction is authorised provided the source is acknowledged._ 

So from my understanding we can refer to the list and even its content. However not all lists in SPOR are owned by EMA.

I like having the lists as instances of RMSControlledVocabulary, but we have to look at the copy right conditions. 

For shelf life the description is:
_1.1 Description
This list contains the description of the condition of the medicinal product under which the given time for the shelf life is applicable.
Examples: "Shelf life after incorporation into meal or pelleted feed"; "Shelf life in unit-dose dispensing". 
The definition of shelf life (also known as expiration dating period) according to ICH Q1A (R2) and CPMP/ICH/2736/99 is: 
The time period during which a drug product is expected to remain within the approved shelf life specification, provided that it is stored under the conditions defined on the container level.
The shelf life should be given for the medicinal product as packaged for sale and after dilution or reconstitution or after first opening if appropriate.
Consider also the information available in:
EMEA/CVMP/846/99 - Note for Guidance on Stability testing of existing active substances and related finished products – currently under revision
CVMP/VICH/899/99-Rev.1 - VICH GL3: Guideline on Stability: Stability testing of new veterinary drug substances and medicinal products
EMEA/CVMP/453/01 - Note for Guidance on Start of shelf-life of the finished dosage form list indicates the possible areas of business that the Term can be applied to._


I have also downloaded the list in XML format
The list information is 
`
  <list-information>
    <list-id id="100000073343">
      <link href="https://spor.ema.europa.eu/v1/lists/100000073343"/>
    </list-id>
    <list-name>Shelf Life Type</list-name>
    <list-status code="CURRENT"/>
    <terms-link>
      <link href="https://spor.ema.europa.eu/v1/lists/100000073343/terms"/>
    </terms-link>
    <is-exportable>true</is-exportable>
    <terms-summaries-link>
      <link href="https://spor.ema.europa.eu/v1/lists/100000073343/term-summaries"/>
    </terms-summaries-link>
    <visibility code="PUBLIC"/>
    <domains>
      <domain id="100000000014" name="Human and Veterinary use" short-name="H&amp;V" status="CURRENT">
        <link href="https://spor.ema.europa.eu/v1/lists/100000000004/terms/100000000014"/>
      </domain>
    </domains>
    <list-operational-attributes version-number="12" created-on="2008-12-02T00:00:00+01:00" modified-on="2023-02-28T14:22:19.351+01:00"/>
    <list-documents>
      <list-document name="Shelf Life Type" rel="DOCUMENT" href="https://spor.ema.europa.eu/v1/documents/75?app-domain=RMS&amp;doc-type=LIST-INFO" mime-type="application/vnd.openxmlformats-officedocument.wordprocessingml.document" document-id="75"/>
    </list-documents>
    <owner>EMA</owner>
  </list-information>`
As you can see the list has a proper IRI:
https://spor.ema.europa.eu/v1/lists/100000073343
without any hash inside

This is also the case for the terms themselves, for example
`
    <controlled-term spor:rowid="68067" xmlns:types="http://genericparallel/types" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:spor="http://ema.europa.eu/schema/spor">
      <term-id id="100000073403">
        <link href="https://spor.ema.europa.eu/v1/lists/100000073343/terms/100000073403"/>
      </term-id>
      <term-names>
        <term-name>
          <name translation-status-code="CURRENT" modified-on="2021-11-26T16:17:26.562Z" lang="et" translation-id="13730004">Kõlblikkusaeg</name>
        </term-name>
        <term-name>
          <name translation-status-code="CURRENT" modified-on="2023-02-28T13:22:00.246Z" lang="es" translation-id="22130010">Período de validez del medicamento acondicionado para la venta</name>
        </term-name>
        <term-name>
          <name translation-status-code="CURRENT" modified-on="2010-06-11T06:29:44Z" lang="en" translation-id="760823">Shelf life of the medicinal product as packaged for sale</name>
        </term-name>
        <term-name>
          <name translation-status-code="CURRENT" modified-on="2010-06-11T06:29:43Z" lang="de" translation-id="760825">Haltbarkeit des Arzneimittels in der Originalverpackung</name>
        </term-name>
      </term-names>
      <short-names>
        <short-name>
          <name translation-status-code="CURRENT" modified-on="2010-06-11T06:29:44Z" lang="en" translation-id="760824">closed package</name>
        </short-name>
        <short-name>
          <name translation-status-code="CURRENT" modified-on="2010-06-11T06:29:43Z" lang="de" translation-id="760826">originalverschlossene Packung</name>
        </short-name>
      </short-names>
      <status code="CURRENT" modified-by="ema" modified-on="2008-12-03T08:24:22Z" spor:rowid="80568"/>
      <operational-attributes version-number="4" modified-on="2023-02-28T14:22:00.105+01:00" created-on="2008-12-03T09:24:22.000+01:00" is-major-version="false"/>
      <visibility code="PUBLIC"/>
      <domains>
        <domain id="100000000014" name="Human and Veterinary use" short-name="H&amp;V" status="CURRENT" spor:rowid="76817">
          <link href="https://spor.ema.europa.eu/v1/lists/100000000004/terms/100000000014"/>
        </domain>
      </domains>
    </controlled-term>
`
The term iri is https://spor.ema.europa.eu/v1/lists/100000073343/terms/100000073403 (from controlled-term/term-id/link)

As usual in the EU, the terms are translated into the different languages and each translation has its own ID.
but important is that the term has an IRI without inline hashes that is usable in RDF.
There is no need for a Pistoia alias IRI anymore. It is not required that each IRI is resolvable in the way of linked data.

2023-08-10 09:23 UTC, tw-osthus commented
[RMS Conceptual Data Model for MDM (1).pdf](https://github.com/edmcouncil/idmp/files/12311162/RMS.Conceptual.Data.Model.for.MDM.1.pdf)

for reference this is the conceptual data model for RMS.

2023-08-10 09:50 UTC, tw-osthus requested changes

2023-08-10 09:50 UTC, tw-osthus commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
>  		<cmns-av:directSource rdf:resource="https://spor.ema.europa.eu/rmswi/#/lists/100000072052/terms"/>
use the IRI as I have explained in my comments. The inline hash is probably some artifact of the service implementation

2023-08-10 09:50 UTC, tw-osthus commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +	<owl:ObjectProperty rdf:about="&idmp-spor;hasSPORTermName">
A SPOR term has not preferred name per se. It has multiple names in different languages.
The model is
`
<https://spor.ema.europa.eu/v1/lists/100000073343/terms/100000073403>
          a idmp-spor:SPORControlledTerm;
            idmp-spor:hasSPORTermName [ 
                cmns-dsg:hasName "Kõlblikkusaeg"; 
                idmp-spor:hasLangugage lcc-lang:et 
            ],
           [ 
               cmns-dsg:hasName "Shelf life of the medicinal product as packaged for sale"; 
               idmp-spor:hasLanguage lcc-lang:en 
           ] .
`
vs.
`
<https://spor.ema.europa.eu/v1/lists/100000073343/terms/100000073403>
          a idmp-spor:SPORControlledTerm;
            idmp-spor:hasSPORTermName 
              "Kõlblikkusaeg"@et, 
             "shelf life of the medicinal product as packaged for sale"@en .
`
`The translation is a node, which has its own id, and more important, the term status is attached to the translation not the controlled term (concept).

see the xml export

2023-08-10 09:58 UTC, tw-osthus commented
[export-100000073343.zip](https://github.com/edmcouncil/idmp/files/12311482/export-100000073343.zip)

XML export of the shelf life list for reference

2023-08-10 13:52 UTC, avilesg submitted a review, later dismissed

2023-08-10 15:13 UTC, ElisaKendall commented
> the SubstancesProductsOrganisationsReferential.rdf ontology needs legal review.
> 
> I have access to SPOR and the license for the SPOR list for shelf life type: _1.8. Copyright and other disclaimers The content of this list and associated intellectual property rights were developed under projects funded by the EMA therefore becoming the property of the EMA. Reproduction is authorised provided the source is acknowledged._
> 
> So from my understanding we can refer to the list and even its content. However not all lists in SPOR are owned by EMA.
> 
> I like having the lists as instances of RMSControlledVocabulary, but we have to look at the copy right conditions.
> 
> For shelf life the description is: _1.1 Description This list contains the description of the condition of the medicinal product under which the given time for the shelf life is applicable. Examples: "Shelf life after incorporation into meal or pelleted feed"; "Shelf life in unit-dose dispensing". The definition of shelf life (also known as expiration dating period) according to ICH Q1A (R2) and CPMP/ICH/2736/99 is: The time period during which a drug product is expected to remain within the approved shelf life specification, provided that it is stored under the conditions defined on the container level. The shelf life should be given for the medicinal product as packaged for sale and after dilution or reconstitution or after first opening if appropriate. Consider also the information available in: EMEA/CVMP/846/99 - Note for Guidance on Stability testing of existing active substances and related finished products – currently under revision CVMP/VICH/899/99-Rev.1 - VICH GL3: Guideline on Stability: Stability testing of new veterinary drug substances and medicinal products EMEA/CVMP/453/01 - Note for Guidance on Start of shelf-life of the finished dosage form list indicates the possible areas of business that the Term can be applied to._
> 
> I have also downloaded the list in XML format The list information is ` <list-information> <list-id id="100000073343"> <link href="https://spor.ema.europa.eu/v1/lists/100000073343"/> </list-id> <list-name>Shelf Life Type</list-name> <list-status code="CURRENT"/> <terms-link> <link href="https://spor.ema.europa.eu/v1/lists/100000073343/terms"/> </terms-link> <is-exportable>true</is-exportable> <terms-summaries-link> <link href="https://spor.ema.europa.eu/v1/lists/100000073343/term-summaries"/> </terms-summaries-link> <visibility code="PUBLIC"/> <domains> <domain id="100000000014" name="Human and Veterinary use" short-name="H&amp;V" status="CURRENT"> <link href="https://spor.ema.europa.eu/v1/lists/100000000004/terms/100000000014"/> </domain> </domains> <list-operational-attributes version-number="12" created-on="2008-12-02T00:00:00+01:00" modified-on="2023-02-28T14:22:19.351+01:00"/> <list-documents> <list-document name="Shelf Life Type" rel="DOCUMENT" href="https://spor.ema.europa.eu/v1/documents/75?app-domain=RMS&amp;doc-type=LIST-INFO" mime-type="application/vnd.openxmlformats-officedocument.wordprocessingml.document" document-id="75"/> </list-documents> <owner>EMA</owner> </list-information>` As you can see the list has a proper IRI: https://spor.ema.europa.eu/v1/lists/100000073343 without any hash inside
> 
> This is also the case for the terms themselves, for example `<controlled-term spor:rowid="68067" xmlns:types="http://genericparallel/types" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:spor="http://ema.europa.eu/schema/spor"> <term-id id="100000073403"> <link href="https://spor.ema.europa.eu/v1/lists/100000073343/terms/100000073403"/> </term-id> <term-names> <term-name> <name translation-status-code="CURRENT" modified-on="2021-11-26T16:17:26.562Z" lang="et" translation-id="13730004">Kõlblikkusaeg</name> </term-name> <term-name> <name translation-status-code="CURRENT" modified-on="2023-02-28T13:22:00.246Z" lang="es" translation-id="22130010">Período de validez del medicamento acondicionado para la venta</name> </term-name> <term-name> <name translation-status-code="CURRENT" modified-on="2010-06-11T06:29:44Z" lang="en" translation-id="760823">Shelf life of the medicinal product as packaged for sale</name> </term-name> <term-name> <name translation-status-code="CURRENT" modified-on="2010-06-11T06:29:43Z" lang="de" translation-id="760825">Haltbarkeit des Arzneimittels in der Originalverpackung</name> </term-name> </term-names> <short-names> <short-name> <name translation-status-code="CURRENT" modified-on="2010-06-11T06:29:44Z" lang="en" translation-id="760824">closed package</name> </short-name> <short-name> <name translation-status-code="CURRENT" modified-on="2010-06-11T06:29:43Z" lang="de" translation-id="760826">originalverschlossene Packung</name> </short-name> </short-names> <status code="CURRENT" modified-by="ema" modified-on="2008-12-03T08:24:22Z" spor:rowid="80568"/> <operational-attributes version-number="4" modified-on="2023-02-28T14:22:00.105+01:00" created-on="2008-12-03T09:24:22.000+01:00" is-major-version="false"/> <visibility code="PUBLIC"/> <domains> <domain id="100000000014" name="Human and Veterinary use" short-name="H&amp;V" status="CURRENT" spor:rowid="76817"> <link href="https://spor.ema.europa.eu/v1/lists/100000000004/terms/100000000014"/> </domain> </domains> </controlled-term>` The term iri is https://spor.ema.europa.eu/v1/lists/100000073343/terms/100000073403 (from controlled-term/term-id/link)
> 
> As usual in the EU, the terms are translated into the different languages and each translation has its own ID. but important is that the term has an IRI without inline hashes that is usable in RDF. There is no need for a Pistoia alias IRI anymore. It is not required that each IRI is resolvable in the way of linked data.

This is interesting - thank you for the revised URIs. I'll update the ontology to reflect these rather than what is shown in the online version.

2023-08-10 15:15 UTC, ElisaKendall commented
@tw-osthus With respect to the copyright issues in lists from other organizations, I think that's above my pay grade :). We will need someone from Pistoia to check that the values for the lists can all be generated in the Accurids data sets, but we have not included the values for the terms in the ontology, so I think we are ok in that regard.

2023-08-10 17:24 UTC, ElisaKendall commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
>  		<cmns-av:directSource rdf:resource="https://spor.ema.europa.eu/rmswi/#/lists/100000072052/terms"/>
Done

2023-08-11 01:04 UTC, ElisaKendall commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +	<owl:ObjectProperty rdf:about="&idmp-spor;hasSPORTermName">
@tw-osthus The names are now nodes but I have not yet added the translation details. However, there is a higher level status for the term in addition to the translation details, which is what I've included. In the ontology, we have a name which has a string value now, and that string value can be expressed in any language as desired. I think we can add the translation information in another pass.

2023-08-11 10:46 UTC, tw-osthus commented
I would map a SPOR RMS list to a MVF vocabulary and a SPOR RMS term to an MVF entry.

SPOR terms can be hierarchical, which fits concept better than term. It also aligns with SKOS.

here is my take on it in Manchester syntax like notation:
`
## list
class idmp-spor:SPORRMSList rdfs:subClassOf idmp-spor:SPORList
       rdfs:label "SPOR RMS list"
       cmns-id:isIdentifiedBy   exactly 1 idmp-spor:SPORRMSListIdentifier 
       cmns-dsg:isSignifiedBy  exactly 1 idmp-spor:SPORRMSListName
       idmp-spor:hasDomain  exactly 1 idmp-spor:SPORRMSDomain
       idpm-spor:hasStatus     exactly 1 idmp-spor:SPORRMSStatus 
       idpm-spor:hasVisibility  exaclty 1 idmp-spor:SPORRMSVisibility 


## term
class idmp-spor:SPORRMSTerm rdfs:subClassOf mvf:MVFEntry .
       rdfs:label "SPOR RMS term"
       cmns-av:synonym "SPOR RMS controlled term"
       cmns-col:isIncludedIn          min 1 idmp-spor:SPORRMSList
       mvf:hasBroaderEntry           min 0 idmp-spor:SPORRMSTerm
       mvf:hasNarrowerEntry         min 0 idmp-sporSPORRMSTerm
       idpm-spor:hasSPORStatus   exactly  1 idmp-spor:SPORRMSStatus 

## term name      
class idmp-spor:SPORRMSTermName rdfs:subClassOf mvf:VocabularyEntry
       rdfs:label "SPOR RMS term name"
       cmns-col:isIncludedIn only idmp-spor:SPORRMSList 
       cmns-dsg:denotes  exactly 1 idmp-spor:SPORRMSTerm
       mvf:hasLanguage exactly 1 lcc-lr:Language

## other term name
class idmp-spor:SPORRMSOtherTermName rdfs:subClassOf mvf:VocabularyEntry
       rdfs:label "SPOR RMS other term name"
       cmns-col:isIncludedIn only idmp-spor:SPORRMSList 
       cmns-dsg:denotes  exactly 1 idmp-spor:SPORRMSTerm
       mvf:hasLanguage exactly 1 lcc-lr:Language

## short name
class idmp-spor:SPORRMSShortTermName rdfs:subClassOf mvf:VocabularyEntry, mvf:Abbreviation
       rdfs:label "SPOR RMS short term name"
       cmns-col:isIncludedIn only idmp-spor:SPORRMSList 
       cmns-dsg:denotes  exactly 1 idmp-spor:SPORRMSTerm
       mvf:hasLanguage exactly 1 lcc-lr:Language

      
instance idpm-spor:SPORRMSDomainVocabulary     rdf:type idmp-spor:SPORRMSList .

instance idpm-spor:SPORRMSStatusVocabulary        rdf:type idmp-spor:SPORRMSList .

instance idpm-spor:SPORRMSVisibilityVocabulary    rdf:type idmp-spor:SPORRMSList .

## domain
class idmp-spor:SPORRMSDomain rdfs:subClassOf idmp-spor:SPORRMSTerm 
        cmns-col:isIncludedIn value idmp-spor:SPORRMSDomainVocabulary 
.
## status
class idmp-spr:SPORRMSStatus rdfs:subClassOf idmp-spor:SPORRMSTerm, mvf:TermStatus 
        cmns-col:isIncludedIn value idmp-spor:SPORRMSStatusVocabulary  
    
## visibility    
class idmp-spr:SPORRMSVisibility rdfs:subClassOf idmp-spor:SPORRMSTerm 
        cmns-col:isIncludedIn value idmp-spor:SPORRMSVisibilityVocabulary  
 
## ids
class idmp-spor:SPORRMSTermIdentifier rdfs:subClassOf cmns-id:RegisteredIdentifier
     cmns-id:identifies exactly 1 idmp-spor:SPORRMSTerm

class idmp-spor:SPORRMSListIdentifier rdfs:subClassOf cmns-id:RegisteredIdentifer
     cmns-id:identifies exactly 1 idmp-spor:SPORRMSList

class idmp-spor:SPORRMSListOID rdfs:subClassOf cmns-id:RegisteredIdentifier
     cmns-id:identifies exactly 1 idmp-spor:SPORRMSList

object property idmp-spor:hasSPORStatus
    rdfs:range idmp-spor:SPORRMSStatus 
   
object property idmp-spor:hasSPORDomain
    rdfs:subPropertyOf mvf:hasContextualEntry
    rdfs:range idmp-spor:SPORRMSDomain

object property idmp-spor:hasSPORVisibility
   rdfs:range idmp-spor:SPORRMSVisibility   
`

For reference the SPOR API Specification EMA/241514/2016: pages 68-
specifies what lists, terms and translations are composed of.

>
> ## 7. Resources
>
> ### List 7.1.
>
> List is a collection of related terms, e.g. countries list, units of measure list. List has additional properties like description, list owner and other. RMS manages multiple lists.
>List schema definitions are in the attached XML Schema.
>This schema is authoritative source of information on resource properties for this API.
>
>List properties can be represented as:
>
>|                                                                 |                                               |
>|--------------------------------------------|---------------------------------|
>| Collection of summary list information | Global element: \<list-of-list> |
>| Detailed information on a single list     | Global element: \<list-details>|
>
>Please see Annex II on guidance on how to navigate between above elements.
>
>Summary list information has following properties (non-exhaustive, see schema for details):
>| Property                                   | Card. | Type              | Description |
>|----------------------------------|-------|----------------|--------------|
>| \<list-id>                                   |  [1]     | Complex        |List identifier and a link to list detailed information Format: nnnnnnnnnnnn Example: 100000155052 |
>| \<list-name>                              |  [1]     | String             |Name of the list |
>| \<list-short-name>                    | [0..1]  | String             | Short name of the list | 
>| \<list-status>                             | [1]     | Enumeration  | Status of the list |
>| \<terms-link>                            | [1]     | Complex        | Link to a complete collection of terms for a given list |
>| \<terms-summaries-link>         | [1]      | Complex        | Link to a collection of terms summaries for a given list | 
>| \<visibility>                                | [1]      | Enumeration  | Data visibility classification of the list |
>| \<domains>                               | [0..1]  | Collection      | Domains for which the list is defined |
>| \<list-operational-attributes>    | [1]     | Complex        |  Operational and lifecycle attributes of the list | 
>| \<list-documents>                     | [0..1]  |Complex         | Collection of documents associated with the list |
>| \<list-description>                     | [0..1]  | String             |  Description of the list  |
>| \<owner>                                   | [0..1]  | String             | The entity owning the vocabulary and its values  |
>| \<version-provided-by-owner> | [0..1]  | String             |The version under the owner published a given list |
>
>Detailed list information extends the above by (non-exhaustive, see schema for details):
>
>| Property                                            |  Card. |  Type      |  Description  |
>|----------------------------------------|--------|----------|----------------| 
>| \<oid>                                              |   [0..1] | anyURI   |  Globally unique object identifier defined for the list | 
>| \<list-level-definition>                     |    [0..1]| Complex | Definitions of named list levels for a given list. Note: individual terms will be assigned to lists levels using list-level assignment element in controlled-term |
>| \<extended-relationship-definitions> | [0..1] | Complex  | Collection of definitions of relationships to other lists |
>| \<extended-attributes-definitions>    |[0..1]  | Complex  | Collection of extended attribute definitions defined for a given list |
>
>### Term 7.2.
>
>Term is a word or phrase used to describe a thing or to express a concept. All RMS terms have a name in English and possible translations of this name to other languages. Related terms are grouped into lists.
>Term schema definitions are in the attached XML Schema.
>This schema is authoritative source of information on resource properties for this API.
>
>Term properties can be represented as:
>
>|      |      |
>|----|----|
>| Collection of summary terms information from a single list. |       Global element: \<controlled-terms-list-summary>|
>|  Contains additional information on Collection of controlled terms details from a single list |   Global element: \<controlled-terms-list> |
>|  Collection of controlled term details or summaries from multiple lists |   Global element: \<controlled-terms [...]

2023-08-11 11:36 UTC, tw-osthus commented
I have a similar controlled vocabulary applicable in the US jurisdiction used for races and ethnicities.
It is managed by the Centers of Disease Control and Prevention (CDC), which is an agency of the U.S. Department of Health and Human Services. They provide a service similar to SPOR RMS called PHIN-VADS. It is used by HL7 for this purpose.
[https://phinvads.cdc.gov/vads/SearchVocab.action](https://phinvads.cdc.gov/vads/SearchVocab.action)

One of the vocabularies or code systems (as they call them) is 
Races & Ethnicities - CDC
```

named individual idmp-phin:RaceAndEthnicityCDC rdf:type idmp-phin:CodeSystem
    rdfs:label "Race & Ethnicity - CDC"
    cmns-av:synonym "CDC Race Category And Ethnicity Group" 
    cmns-id:isIdentifiedBy idmp-phin:RaceAndEthnicityCDCCodeSystemIdentifier
    cmns-id:isIdentifiedBy idmp-phin:RaceAndEthnicityCDCCodeSystemOID
 
named individual idmp-phin:RaceAndEthnicityCDCCodeSystemIdentifier rdf:type idmp-phin:PHINCodeSystemIdentifier 
   cmns-txt:hasTextValue "PH_RaceAndEthnicity_CDC" 
named individual idmp-phin:RaceAndEthnicityCDCCodeSystemOID rdf:type idmp-phin:PHINCodeSystemOID 
   cmns-txt:hasTextValue "2.16.840.1.113883.6.238" 

class idmp-phin:RaceAndEthnicityCDCConcept rdfs:subClassOf idmp-phin:PHINConcept
      cmns-col:isIncludedIn value idmp-phin:RaceAndEthnicitiesCDC

class idmp-phin:PHINConcept rdfs:subClassOf mvf:MVFEntry .
class idmp-phin:PHINCodeSystem rdfs:subClassOf mvf:MVFVocabulary

```
I have used the terms from the source, to avoid confusion, but they are mapped to the MVF and CMNS classes.

2023-08-11 11:59 UTC, tw-osthus commented
In the IDMP ontologies we may want to reference the concepts (MVF entries) directly, instead of using code elements, that refer to them. There is are differences between an MVF entry as part of an MVF vocabulary and a code element as part of a code set.

The IDMP standard on datatypes mandates the use of ISO21090:CD datatype, so if we want to stay close to the standard then the code element must be an ISO 21090 concept descriptor.

So we need a mapping between MVF and ISO 21090.
In a ISO 21090 concept descriptor the name is a datatype property.
In an MVF entry the name is a MVF vocabulary entry, which has a textual name (or by inheritance a cmns-txt:hasTextValue) 

MVF is more like SKOS-XL vs ISO 21090 is like SKOS.

SKOS is by the way another vocabulary language, that is in widespread use. This makes it event more important to standardize on the way how we work with concepts for classification, given that it is so common practice in IDMP.

2023-08-11 12:00 UTC, tw-osthus requested changes

2023-08-11 13:39 UTC, tw-osthus commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +		</rdfs:subClassOf>
There is also another semantic problem:
mvf:hasLanguage expects a lcc-lr:Language, but lcc-639-1:English is an instance of lcc-lr:Alpha2LanguageCode which is a subclass of lcc-lr:LanguageIdentifier.

We often use identifiers as proxy reference for thing being identified, but they are semantically not identical.
lcc-lr:LanguageIdentifier should be disjoint with lcc-lr:Language.

correct is
```
<rdfs:subClassOf>
   <owl:Restriction>
      <owl:onProperty rdf:resource="&mvf;hasLanguage/>
     <owl:someValueOf>
           <owl:Restriction>
                 <owl:onProperty rdf:resource="&cmns-id;isIdentifiedBy">
                 <owl:hasValue rdf:resource="&lcc-639-1;English/>
           <owl:Restriction>
     <owl:someValueOf>
   <owl:Restriction>
```
This is a bit awkward. So I recommend that lcc-639-1 also provides IRIs for the language itself changes the ontology, so that the IRI lcc-639-1:English is the language not the language identifier.



</rdfs:subClassOf>

2023-08-11 14:59 UTC, ElisaKendall commented
> I would map a SPOR RMS list to a MVF vocabulary and a SPOR RMS term to an MVF entry.
> 
> SPOR terms can be hierarchical, which fits concept better than term. It also aligns with SKOS.
> 
> here is my take on it in Manchester syntax like notation:
> 
> ## list
> ```
> class idmp-spor:SPORRMSList rdfs:subClassOf mvf:Vocabulary
>        rdfs:label "SPOR RMS list"
>        cmns-id:isIdentifiedBy   exactly 1 idmp-spor:SPORRMSListIdentifier 
>        cmns-dsg:isSignifiedBy  exactly 1 idmp-spor:SPORRMSListName
>        idmp-spor:hasDomain  exactly 1 idmp-spor:SPORRMSDomain
>        idpm-spor:hasStatus     exactly 1 idmp-spor:SPORRMSStatus 
>        idpm-spor:hasVisibility  exaclty 1 idmp-spor:SPORRMSVisibility 
> ```
> 
> ## term
> ```
> class idmp-spor:SPORRMSTerm rdfs:subClassOf mvf:MVFEntry .
>        rdfs:label "SPOR RMS term"
>        cmns-av:synonym "SPOR RMS controlled term"
>        cmns-col:isIncludedIn          min 1 idmp-spor:SPORRMSList
>        mvf:hasBroaderEntry           min 0 idmp-spor:SPORRMSTerm
>        mvf:hasNarrowerEntry         min 0 idmp-sporSPORRMSTerm
>        idpm-spor:hasSPORStatus   exactly  1 idmp-spor:SPORRMSStatus 
> ```
> 
> ## term name
> ```
> class idmp-spor:SPORRMSTermName rdfs:subClassOf mvf:VocabularyEntry
>        rdfs:label "SPOR RMS term name"
>        cmns-col:isIncludedIn only idmp-spor:SPORRMSList 
>        cmns-dsg:denotes  exactly 1 idmp-spor:SPORRMSTerm
>        mvf:hasLanguage exactly 1 lcc-lr:Language
> ```
> 
> ## other term name
> ```
> class idmp-spor:SPORRMSOtherTermName rdfs:subClassOf mvf:VocabularyEntry
>        rdfs:label "SPOR RMS other term name"
>        cmns-col:isIncludedIn only idmp-spor:SPORRMSList 
>        cmns-dsg:denotes  exactly 1 idmp-spor:SPORRMSTerm
>        mvf:hasLanguage exactly 1 lcc-lr:Language
> ```
> 
> ## short name
> ```
> class idmp-spor:SPORRMSShortTermName rdfs:subClassOf mvf:VocabularyEntry, mvf:Abbreviation
>        rdfs:label "SPOR RMS short term name"
>        cmns-col:isIncludedIn only idmp-spor:SPORRMSList 
>        cmns-dsg:denotes  exactly 1 idmp-spor:SPORRMSTerm
>        mvf:hasLanguage exactly 1 lcc-lr:Language
> ```
> 
> ## domain
> ```
> class idmp-spor:SPORRMSDomain rdfs:subClassOf idmp-spor:SPORRMSTerm 
>         cmns-col:isIncludedIn value idmp-spor:SPORRMSDomainVocabulary 
> ```
> 
> ## status
> ```
> class idmp-spr:SPORRMSStatus rdfs:subClassOf idmp-spor:SPORRMSTerm, mvf:TermStatus 
>         cmns-col:isIncludedIn value idmp-spor:SPORRMSStatusVocabulary  
> ```
> 
> ## visibility
> ```
> class idmp-spr:SPORRMSVisibility rdfs:subClassOf idmp-spor:SPORRMSTerm 
>         cmns-col:isIncludedIn value idmp-spor:SPORRMSVisibilityVocabulary  
> ```
> 
> ## ids
> ### SPOR RMS term identifier
> ```
> class idmp-spor:SPORRMSTermIdentifier rdfs:subClassOf cmns-id:RegisteredIdentifier
>       rdfs:label "SPOR RMS term identifier"
>       cmns-id:identifies exactly 1 idmp-spor:SPORRMSTerm
> ```
> 
> ### SPOR RMS list identifier
> ```
> class idmp-spor:SPORRMSListIdentifier rdfs:subClassOf cmns-id:RegisteredIdentifer
>      rdfs:label "SPOR RMS list identifier"
>      cmns-id:identifies exactly 1 idmp-spor:SPORRMSList
> ```
> 
> ### list OID
> ```
> class idmp-spor:SPORRMSListOID rdfs:subClassOf cmns-id:RegisteredIdentifier
>      rdfs:label "SPOR RMS list OID"
>      cmns-id:identifies exactly 1 idmp-spor:SPORRMSList
> ```
> 
> ## predefined lists used and defined in SPOR itself
> ### domain list 100000000004
> we might want to add some predefined instances that are unlikely to change
> 
> ```
> named individual idpm-spor:SPORRMSDomainVocabulary     rdf:type idmp-spor:SPORRMSList 
>     cmns-id:isIdentifiedBy idmp-spor:SPORRMSDomainListId
> 
> named individual idmp-spor:SPORRMSDomainListId rdf:type idmp-spor:SPORRMSListIdentifier
>     cmns-txt:hasTextValue "100000000004"
> ```
> 
> ### status list
> ```
> named individual idpm-spor:SPORRMSStatusVocabulary        rdf:type idmp-spor:SPORRMSList 
> ```
> 
> ### visibility list
> ```
> named individual idpm-spor:SPORRMSVisibilityVocabulary    rdf:type idmp-spor:SPORRMSList 
> ```
> 
> ## properties
> ### has status
> ```
> object property idmp-spor:hasSPORStatus
>     rdfs:subPropertyOf mvf:hasStatus
>     rdfs:label "has SPOR status"
>     rdfs:range idmp-spor:SPORRMSStatus 
> ```
> 
> ### has domain
> ```
> object property idmp-spor:hasSPORDomain
>     rdfs:subPropertyOf mvf:hasContextualEntry
>     rdfs:label "has SPOR domain"
>     rdfs:range idmp-spor:SPORRMSDomain
> ```
> 
> ### has visibility
> ```
> object property idmp-spor:hasSPORVisibility
>     rdfs:subPropertyOf cmns-cls:characterizes
>    rdfs:label "has SPOR visibility"
>    rdfs:range idmp-spor:SPORRMSVisibility   
> ```
> 
> For reference the SPOR API Specification EMA/241514/2016: pages 68- specifies what lists, terms and translations are composed of.
> 
> > ## 7. Resources
> > ### List 7.1.
> > List is a collection of related terms, e.g. countries list, units of measure list. List has additional properties like description, list owner and other. RMS manages multiple lists.
> > List schema definitions are in the attached XML Schema.
> > This schema is authoritative source of information on resource properties for this API.
> > List properties can be represented as:
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > Collection of summary list information
> > Global element: <list-of-list>
> > 
> > 
> > Detailed information on a single list
> > Global element: <list-details>
> > 
> > 
> > 
> > Please see Annex II on guidance on how to navigate between above elements.
> > Summary list information has following properties (non-exhaustive, see schema for details):
> > 
> > 
> > 
> > Property
> > Card.
> > Type
> > Description
> > 
> > 
> > 
> > 
> > <list-id>
> > [1]
> > Complex
> > List identifier and a link to list detailed information Format: nnnnnnnnnnnn Example: 100000155052
> > 
> > 
> > <list-name>
> > [1]
> > String
> > Name of the list
> > 
> > 
> > <list-short-name>
> > [0..1]
> > String
> > Short name of the list
> > 
> > 
> > <list-status>
> > [1]
> > Enumeration
> > Status of the list
> > 
> > 
> > <terms-link>
> > [1]
> > Complex
> > Link to a complete collection of terms for a given list
> > 
> > 
> > <terms-summaries-link>
> > [1]
> > Complex
> > Link to a collection of terms summaries for a given list
> > 
> > 
> > <visibility>
> > [1]
> > Enumeration
> > Data visibility classification of the list
> > 
> > 
> > <domains>
> > [0..1]
> > Collection
> > Domains for which the list is defined
> > 
> > 
> > <list-operational-attributes>
> > [1]
> > Complex
> > Operational and lifecycle attributes of the list
> > 
> > 
> > <list-documents>
> > [0..1]
> > Complex
> > Collection of documents associated with the list
> > 
> > 
> > <list-description>
> > [0..1]
> > String
> > Description of the list
> > 
> > 
> > <owner>
> > [0..1]
> > String
> > The entity owning the vocabulary and its values
> > 
> > 
> > <version-provided-by-owner>
> > [0..1]
> > String
> > The version under the owner published a given list
> > 
> > 
> > 
> > Detailed list information extends the above by (non-exhaustive, see schema for details):
> > 
> > 
> > 
> > Property
> > Card.
> > Type
> > Description
> > 
> > 
> > 
> > 
> > <oid>
> > [0..1]
> > anyURI
> > Globally unique object identifier defined for the list
> > 
> > 
> > <list-level-definition>
> > [0..1]
> > Complex
> > Definitions of named list levels for a given list. Note: individual terms will be assigned to lists levels using list-level assignment element in controlled-term
> > 
> > 
> > <extended-relationship-definitions>
> > [0..1]
> > Complex
> > Collection of definitions of relationships to other lists
> > 
> > 
> > <extended-attributes-definitions>
> > [0..1]
> > Complex
> > Collection of extended attribute definitions defined for a given list
> > 
> > 
> > 
> > ### Term 7.2.
> > Term is a word or phrase used to describe a thing or to express a concept. All RMS terms have a name in English and possible translat [...]

2023-08-11 15:01 UTC, ElisaKendall commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +		</rdfs:subClassOf>
@tw-osthus True, but MVF requires a language for the overall vocabulary. The alternative would be to add a value ourselves for not applicable, which I'm not really excited about doing. And, IDMP is in English :).

2023-08-26 21:25 UTC, ElisaKendall commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +		</rdfs:subClassOf>
> There is also another semantic problem: mvf:hasLanguage expects a lcc-lr:Language, but lcc-639-1:English is an instance of lcc-lr:Alpha2LanguageCode which is a subclass of lcc-lr:LanguageIdentifier.
> 
> We often use identifiers as proxy reference for thing being identified, but they are semantically not identical. lcc-lr:LanguageIdentifier should be disjoint with lcc-lr:Language.
> 
> correct is
> 
> ```
> <rdfs:subClassOf>
>    <owl:Restriction>
>       <owl:onProperty rdf:resource="&mvf;hasLanguage/>
>      <owl:someValueOf>
>            <owl:Restriction>
>                  <owl:onProperty rdf:resource="&cmns-id;isIdentifiedBy">
>                  <owl:hasValue rdf:resource="&lcc-639-1;English/>
>            <owl:Restriction>
>      <owl:someValueOf>
>    <owl:Restriction>
> </rdfs:subClassOf>
> ```
> 
> This is a bit awkward. So I recommend that lcc-639-1 also provides alternative IRIs for the languages or changes the ontology, so that the IRI lcc-639-1:English is the language not the language identifier.

Actually, if I load LCC without anything else, lcc-639-1:English is an instance of language, not language identifier. There is an equivalence that a colleague created with the US Library of Congress URI for English, which appears to be an identifier/code, but that also is an instance of Language, not of language identifier. It is possible that in some IDMP example either was used incorrectly though.

2023-08-30 10:20 UTC, tw-osthus requested changes

2023-08-30 10:20 UTC, tw-osthus commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +		<dct:source rdf:resource="https://spor.ema.europa.eu/v1/lists/200000004983/terms/200000004984"/>
why not use the SPOR IRI for the term?
or add
```
<owl:NamedIndividual rdf:about="&idmp-spor;SPOR-DataClassification-Confidential">
   <owl:sameAs rdf:resource="https://spor.ema.europa.eu/v1/lists/200000004983/terms/200000004984"> 
 </owl:NamedIndividual>
```

If we define our own IRIs for concepts managed externally, then we should at least make some alignment/mapping.

dct:source is to weak

2023-08-30 10:20 UTC, tw-osthus commented on ISO/ISO11615-MedicinalProducts.rdf
> +			<owl:Class>
I have made a separate pull request for this. We can close that then.

2023-08-30 11:09 UTC, tw-osthus commented
I have loaded the reference individuals.
The Qlaira example seems not correct.

spor-p:/products//products/00006006-1l-100076135 is and instance of idmp-sub:excipient and and instance of spor-r:/lists/100000072050/terms/100000072082 which is the excipient term in the SPOR list.

The SPOR list contains the different ingredient roles. If we define SPOR lists as vocabularies and SPOR terms an term entries in the vocabulary, then 
spor-p:/products//products/00006006-1l-100076135 is an instance of a instance or in other words this implies punning.

It is not stated that the list is a vocabulary, but we want to or do we imply that the list is an ontology and the list entries are classes?

This would make the integration of SPOR difficult, because then we have to decide for each SPOR list, whether the list contains owl:Classes or owl:NamedIndividuals.

Correct alignment would be 
```
idmp-sub:Excepient
   subclassOf
       cmns-cls:isClassifiedBy value spor-r:/lists/100000072050/terms/100000072082
```
or we allow punning.

BTW: The SPOR IRI must also be fixed for Excipient should be https://spor.ema.europa.eu/v1/lists/100000072050/terms/100000072082
it is still
https://spor.ema.europa.eu/rmswi/#/lists/100000072050/terms/100000072082

2023-08-30 14:58 UTC, ElisaKendall commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +		<dct:source rdf:resource="https://spor.ema.europa.eu/v1/lists/200000004983/terms/200000004984"/>
@tw-osthus There would be too much redundancy I think, if you see the number of individuals this already created. but there is a pattern for minting the IRIs where I did so that is repeatable.

2023-08-30 15:23 UTC, ElisaKendall commented on ISO/ISO11615-MedicinalProducts.rdf
> +			<owl:Class>
@tw-osthus I've merged your change and integrated that into this pull request.

2023-09-01 06:13 UTC, Heiner-Oberkampf requested changes
I reviewed all comments from Thomas and replies from Elisa. 
I think the approach will work and represent CVs accurately - concerns on maintenance and usability (below).
The minting patterns can all be realized with Accurids and SPARQL generate pipeline.

**Request for adaptation to use SPOR and opaque IRIs:**
1. Invention of IRIs with human readable local name for the list rdf:resource="&idmp-spor;SPOR-DomainVocabulary
2. Invention of IRIs with human readable local name for the term rdf:resource="&idmp-spor;SPOR-RecordStatus-Current

Usability concerns:
1. I think we don't need definitions for language labels such as this "SPOR term name, in French, for the RMS record status vocabulary term, Current"
2. It seems overkill to use both hasTextValue ... and rdfs:label on a SPOR TermName
3. Using LLC for language reference in addition to @FR-fr language tags on the string is redundant from my perspective
4. I think we don't need definitions for identifier like "SPOR term identifier for the domain term, Human use" - if this is to conform with the hygiene test than I think they should be more flexible than enforcing this kind of overhead.
5.

2023-09-01 13:10 UTC, tw-osthus commented
> 2\. It seems overkill to use both hasTextValue ... and rdfs:label on a SPOR TermName
> 3\. Using LLC for language reference in addition to @FR-fr language tags on the string is redundant from my perspective
label and text value are different

As per SPOR API specification of the Term resource (7.2) there is one per language for term names (TN) and short names (SN)
> <term-id> [1] Complex Agreed European Identifier, this will be a unique sequential number for each term. Format: nnnnnnnnnnnn Example: 100000155052 
> <term-names> [1] Collection Term names in different languages. Max. one name per language. 
> <short-names> [0..1] Collection Short term names in different languages. Max. one name per language.
> <other-names> [0..1] Collection Other term names in different languages. Multiple names allowed per language

`idmp-spor:SPOR-TN-de-100000000004-100000000014` is the German term name for SPOR term 100000000014. 
It has no SPOR IRI on its own.
Elisa's term IRI scheme works for term names and short names, but not for other names. ONs need another identifier because there can be more then one per language.

It has the rdfs:label "SPOR-TN-de-100000000004-100000000014" 
and cmns-txt:textValue "Anwendung an Mensch und Tier"@de, 
so they are **not** the same and so are therefore not redundant.

We could make 1 name term and have multiple hasTextValues with different language tags, but the restriction on mvf:Term which idmp-spor:TermName derives from does not allow this. 
So there are multiple term names per term, one per language. Now with a name per language, we should explicitly use mvf:hasLanguage, because we no longer talk about a langString literal.
I disagree that mvf:hasLanguage is redundant if it is not a langString literal.


But should the rdfs:label of a name not be the same as its cmns-txt:textValue? 
Why not use "Anwendung an Mensch und Tier"@de also the rdfs:label? 
We can specify that the textual representation of a name is always in cmns-txt:hasTextValue, which might be non-English and we can drop the requirement for having an rdfs:label for names, 
becaue then rdfs:label or cmns-txt:textValue would be redundant. The problem is, that we do not know, because we left it out of our guidelines.
 
For classes and properties we have a clear guideline, but what about instances? 

This example rdfs:label uses an arrangement of codes, that can be understood, but can you remember what 100000000014 is? 
So what advantage other then being shorter then the IRI does this kind of label provide over the IRI? 
When working with Protege, I use the feature to display the rdfs:label instead of the IRI, but that does not help me here a lot. 
I cannot see that I had wrongly chosen Vetinerary use, instead of Human use, because I mistyped the code. However as someone how does not understand Bulgarian, 
it would not help to see the Bulgarian translation as rdfs:label either. 

So what to use as rdfs:label is not an easy decision. If we do not specify, what the rdfs:label of a name should be, then anyone will do it differently 
and that does not help at all. Names can have identifiers (codes) such as the term and translation id, which together probably uniquely identify a term name 
and that could be the rdfs:label, but how should they be composed into a single consistent string if there are more then one code or none?

The term names (TN), short names (SN) and other names (ON) do not have official SPOR IRIs. They are locally identified by their SPOR name type (TermName, ShortName,OtherName)
and by their language (or translation id), but for ON also by the name itself.  

The IRI schema that Elisa has used captures all identifying parts of the term name and the short name which are term (as concept), type of name and language, but not for other names. 
It is an IRI schema owned by the Pistoia alliance, by using the idmp-spor prefix.

For the terms in SPOR there exists an official SPOR IRI, which we should prefer to use, instead of defining our own. 
However for the term names there does not exist an API that does dig deeper then the term level. 
So **if** we need an IRI for the term name, **then** we have to make up one of our own.

I would prefer to use 
`{term-IRI}/{term-type}/{language-code}`, e.g.
https://spor.ema.europa.eu/v1/lists/100000000004/terms/100000000012/TN/de for "Anwendung am Menschen"
for this. However it is invasive, as Pistoia does not own and maintain the namespace of SPOR and it is supported by the API. What can be used is an XPointer based URL that fetches
the XML element from the body of the term GET request:
https://spor.ema.europa.eu/v1/lists/100000000004/terms/100000000012#xpointer(//term-names/name@lang='de') for "Anwendung am Menschen". So if **can** use the official URL the reference the
parts, although it is kind of unpleasent to use and it will have to use probably URL escaping to work in RDF.


The next best version is IMHO to define it without IRI and just link it to the term. This means we have to use blank nodes, which may lead to problems with reasoners. 
So instead of blank nodes, we can use Skolem IRIs https://spec.pistoiaalliance.org/.wellknown/genid/....
The term names should never be referenced directly from the outside anyway. 

But if we decide to mint our own Pistoia owned IRIs (and publish them as part of IDMP-O) we should take care that they are aligned. This will introduce some burden on IDMP-O maintenance. 
What if the source term in SPOR is renamed or another translation is added. The current alignment is only provenance via dct:source. So will IDMP-O instances be updated as well?
If IDMP defines IRIs that are aliases, then we can and IMHO should also follow the IDMP guidelines for IRIs which are human friendly. 

The IDMP-O generated IRI should like this, if we are following our guidelines:

idmp-spor:SPOR-Domain, 
idmp-spor:SPOR-Domain-VeterinaryUse, 
idmp-spor:SPOR-Domain-HumanUse, 
idmp-spor:SPOR-Domain-HumanUse-TermName-German
idmp-spor:SPOR-Domain-HumanUse-ShortName-German
idmp-spor:SPOR-Domain-HumanUse-OtherName-German-HumanAndVeterinär

I would still make use of owl:sameAs to align to the official IRIs where possible.

for reference I have uploaded the current XML export for the domain list
[export-100000000004.zip](https://github.com/edmcouncil/idmp/files/12496990/export-100000000004.zip)

2023-09-04 07:20 UTC, tw-osthus submitted a review, later dismissed

2023-09-05 18:27 UTC, avilesg commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +	<owl:ObjectProperty rdf:about="&idmp-spor;hasSPORTermName">
This level of detail is appreciated.  Thank you Thomas and Elisa.

2023-09-05 19:32 UTC, avilesg approved these changes

2023-09-07 04:13 UTC, ElisaKendall commented on ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
> +		<dct:source rdf:resource="https://spor.ema.europa.eu/v1/lists/200000004983/terms/200000004984"/>
@Heiner-Oberkampf @tw-osthus  The new approach uses owl:sameAs to relate the minted term to the SPOR RMS term.

2023-09-07 04:16 UTC, ElisaKendall commented
> > 2. It seems overkill to use both hasTextValue ... and rdfs:label on a SPOR TermName
> > 3. Using LLC for language reference in addition to @FR-fr language tags on the string is redundant from my perspective
> > label and text value are different
> 
> As per SPOR API specification of the Term resource (7.2) there is one per language for term names (TN) and short names (SN)
> 
> > [1] Complex Agreed European Identifier, this will be a unique sequential number for each term. Format: nnnnnnnnnnnn Example: 100000155052
> >  [1] Collection Term names in different languages. Max. one name per language.
> >  [0..1] Collection Short term names in different languages. Max. one name per language.
> >  [0..1] Collection Other term names in different languages. Multiple names allowed per language
> 
> `idmp-spor:SPOR-TN-de-100000000004-100000000014` is the German term name for SPOR term 100000000014. It has no SPOR IRI on its own. Elisa's term IRI scheme works for term names and short names, but not for other names. ONs need another identifier because there can be more then one per language.
> 
> It has the rdfs:label "SPOR-TN-de-100000000004-100000000014" and cmns-txt:textValue "Anwendung an Mensch und Tier"@de, so they are **not** the same and so are therefore not redundant.
> 
> We could make 1 name term and have multiple hasTextValues with different language tags, but the restriction on mvf:Term which idmp-spor:TermName derives from does not allow this. So there are multiple term names per term, one per language. Now with a name per language, we should explicitly use mvf:hasLanguage, because we no longer talk about a langString literal. I disagree that mvf:hasLanguage is redundant if it is not a langString literal.
> 
> But should the rdfs:label of a name not be the same as its cmns-txt:textValue? Why not use "Anwendung an Mensch und Tier"@de also the rdfs:label? We can specify that the textual representation of a name is always in cmns-txt:hasTextValue, which might be non-English and we can drop the requirement for having an rdfs:label for names, because then rdfs:label or cmns-txt:textValue would be redundant. The problem is, that we do not know, because we left it out of our guidelines.
> 
> For classes and properties we have a clear guideline, but what about instances?
> 
> This example rdfs:label uses an arrangement of codes, that can be understood, but can you remember what 100000000014 is? So what advantage other then being shorter then the IRI does this kind of label provide over the IRI? When working with Protege, I use the feature to display the rdfs:label instead of the IRI, but that does not help me here a lot. I cannot see that I had wrongly chosen Veterinary use, instead of Human use, because I mistyped the code. However as someone who does not understand Bulgarian, it would not me help to see the Bulgarian translation as rdfs:label either.
> 
> So what to use as rdfs:label is not an easy decision. If we do not specify, what the rdfs:label of a name should be, then anyone will do it differently and that does not help at all. Names can have identifiers (codes) such as the term and translation id, which together probably uniquely identify a term name and that could be the rdfs:label, but how should they be composed into a single consistent string if there are more then one code or none?
> 
> The term names (TN), short names (SN) and other names (ON) do not have official SPOR IRIs. They are locally identified by their SPOR name type (TermName, ShortName,OtherName) and by their language (or translation id), but for ON also by the name itself.
> 
> The IRI schema that Elisa has used captures all identifying parts of the term name and the short name which are term (as concept), type of name and language, but not for other names. It is an IRI schema owned by the Pistoia alliance, by using the idmp-spor prefix.
> 
> For the terms in SPOR there exists an official SPOR IRI, which we should prefer to use, instead of defining our own. However for the term names there does not exist an API that does dig deeper then the term level. So **if** we need an IRI for the term name, **then** we have to make up one of our own.
> 
> I would prefer to use `{term-IRI}/{term-type}/{language-code}`, e.g. `https://spor.ema.europa.eu/v1/lists/100000000004/terms/100000000012/TN/de` for the German term name "Anwendung am Menschen" for this. However it is invasive, as Pistoia does not own and maintain the namespace of SPOR and it is not supported by the SPOR API.
> 
> What **can** be used is an XPointer based URL that fetches the XML element from the body of the term GET request: `https://spor.ema.europa.eu/v1/lists/100000000004/terms/100000000012#xpointer(//term-names/name@lang='de')` for "Anwendung am Menschen". Using an XPointer fragment based URL is kind of unpleasant to use and it will have to use probably URL escaping to make it work in RDF as IRI.
> 
> The next best version is to define it without IRI and just link it to the term. This means we have to use blank nodes, which may lead to problems with reasoners. Instead of blank nodes, we can use Skolem IRIs of the form `https://spec.pistoiaalliance.org/.wellknown/genid/...` . The term names should never be referenced directly from the outside the ontology anyway. The link should always be the term.
> 
> If we decide to mint our own Pistoia owned IRIs (and publish them as part of IDMP-O) we should take care that they are aligned. This will introduce some burden on IDMP-O maintenance. What if the source term in SPOR is renamed or another translation is added. The current alignment is only provenance via dct:source. So will IDMP-O instances be updated as well? If IDMP defines IRIs that are aliases, then we can and IMHO should also follow the IDMP guidelines for IRIs which are human friendly.
> 
> The IDMP-O generated IRI should look like this, if we are following our guidelines:
> 
> idmp-spor:SPOR-Domain, idmp-spor:SPOR-Domain-VeterinaryUse, idmp-spor:SPOR-Domain-HumanUse, idmp-spor:SPOR-Domain-HumanUse-TermName-German idmp-spor:SPOR-Domain-HumanUse-ShortName-German idmp-spor:SPOR-Domain-HumanUseAndVeterinary-OtherName-German-HumanUndVeterinär
> 
> I would still make use of owl:sameAs to align to the official IRIs where possible.
> 
> for reference I have uploaded the current XML export for the domain list [export-100000000004.zip](https://github.com/edmcouncil/idmp/files/12496990/export-100000000004.zip)

I think the latest version I just committed does exactly this, including owl:sameAs where possible.

2023-09-07 13:33 UTC, tw-osthus approved these changes

2023-09-07 17:13 UTC, Heiner-Oberkampf approved these changes
I still see a problem with defining human readable names for SPOR originating classes like: &idmp-spor;SPOR-RouteOfAdministration as they likely require manual intervention 
Other human readable names in the ontology pattern like &idmp-dtp;ISO21090-ConceptDescriptor are fine.

2023-09-07 17:13 UTC, merged