IDMP-641 add CDC - PHIN Race and Ethnicity with agencies
edmcouncil/idmp pull request #451
Opened 2023-08-14 11:58 UTC by tw-osthus

Description:
* added CDC, PHIN-VADS to na registries
* added Race and Ethnicity vocabulary

2023-08-21 10:32 UTC, mereolog requested changes
It is not possible to check consistency of https://spec.pistoiaalliance.org/idmp/ontology/ISO/20230814/NorthAmericanJurisdiction/PublicHealthInformationNetwork/ - see below the error thrown by Pellet:

```
ERROR  12:29:52  An error occurred during reasoning: Unsupported axiom: Ignoring transitivity and/or complex subproperty axioms for hasBroaderEntry.
org.mindswap.pellet.exceptions.UnsupportedFeatureException: Unsupported axiom: Ignoring transitivity and/or complex subproperty axioms for hasBroaderEntry
	at org.mindswap.pellet.RBox.ignoreTransitivity(RBox.java:813) ~[na:na]
	at org.mindswap.pellet.RBox.prepare(RBox.java:612) ~[na:na]
	at org.mindswap.pellet.KnowledgeBase.prepare(KnowledgeBase.java:1776) ~[na:na]
	at org.mindswap.pellet.KnowledgeBase.consistency(KnowledgeBase.java:1969) ~[na:na]
	at org.mindswap.pellet.KnowledgeBase.isConsistent(KnowledgeBase.java:2061) ~[na:na]
	at org.mindswap.pellet.KnowledgeBase.ensureConsistency(KnowledgeBase.java:2075) ~[na:na]
	at org.mindswap.pellet.KnowledgeBase.classify(KnowledgeBase.java:2083) ~[na:na]
	at com.clarkparsia.pellet.owlapiv3.PelletReasoner.precomputeInferences(PelletReasoner.java:1067) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.precompute(OWLReasonerManagerImpl.java:447) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:388) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
   WARN  12:29:52  Protege terminated reasoner.
```

2023-08-21 10:32 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		<rdfs:type rdf:resource="&idmp-phin;PublicHealthInformationNetworkVocabularyAccessAndDistributionSystemClassificationScheme"/>
PublicHealthInformationNetworkVocabularyAccessAndDistributionSystemClassificationScheme should be declared as an instance of owl:Class.

2023-08-21 10:32 UTC, mereolog commented
See also https://github.com/edmcouncil/idmp/pull/454#issuecomment-1683409590 - a similar comment applies here.

2023-08-21 12:47 UTC, tw-osthus commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		<rdfs:type rdf:resource="&idmp-phin;PublicHealthInformationNetworkVocabularyAccessAndDistributionSystemClassificationScheme"/>
done

2023-08-21 13:21 UTC, mereolog requested changes

2023-08-21 13:21 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		<rdf:subClassOf rdf:resource="&cmns-cls;ClassificationScheme"/>
Since a resource from https://www.omg.org/spec/Commons/Classifiers/ is used, https://www.omg.org/spec/Commons/Classifiers/ ontology needs to be imported.
Currently, OWLAPI (both in Protege and in onto-viewer) is confused as to what cmns-cls:ClassificationScheme might be.

2023-08-21 13:21 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +				<owl:onProperty rdf:resource="&cmns-col;isIncludedIn"/>
https://www.omg.org/spec/Commons/Collections/ needs to be imported - for a reason see the other comment in this review.

2023-08-21 13:21 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +				<owl:onDatatype rdf:resource="https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork/xsd;string"/>
This does not look right - probably it should read <owl:onDatatype rdf:resource="xsd;string"/>.

2023-08-21 13:21 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +				<owl:onDatatype rdf:resource="https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork/xsd;string"/>
This does not look right - probably it should read <owl:onDatatype rdf:resource="xsd;string"/>.

2023-08-21 13:21 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +				<owl:onDatatype rdf:resource="https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork/xsd;string"/>
This does not look right - probably it should read <owl:onDatatype rdf:resource="xsd;string"/>.

2023-08-21 13:27 UTC, mereolog requested changes

2023-08-25 10:55 UTC, tw-osthus commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +				<owl:onDatatype rdf:resource="https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork/xsd;string"/>
yes IRI got corrupted somehow

2023-08-25 10:59 UTC, tw-osthus commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		<cmns-av:directSource rdf:resource="https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.6.238"/>
this seems to be a bug in Pellet. Moved the resource into the content of the element, so that it will be interpreted as string

2023-09-14 10:55 UTC, tw-osthus commented
needs fix of master branch after merge

2023-09-15 09:03 UTC, mereolog requested changes
There is a couple of typos reported in the other comments.

2023-09-15 09:03 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		<rdfs:type rdf:resource="&idmp-phin;VADSCodeSystem"/>
This line should read: `<rdf:type rdf:resource="&idmp-phin;VADSCodeSystem"/>`

2023-09-15 09:03 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		<rdf:subClassOf>
This line should read `<rdfs:subClassOf>`.

2023-09-15 09:03 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		<rdf:subClassOf>
This line should read `<rdfs:subClassOf>`.

2023-09-15 09:03 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		</rdf:subClassOf>
This line should read `</rdfs:subClassOf>`.

2023-09-15 09:03 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		</rdf:subClassOf>
This line should read `</rdfs:subClassOf>`.

2023-09-15 09:20 UTC, mereolog commented
ERROR  11:19:45  An error occurred during reasoning: Cannot do reasoning with inconsistent ontologies!
```
Reason for inconsistency: Literal value "https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.6.238"^^string does not belong to datatype anyURI.
org.mindswap.pellet.exceptions.InconsistentOntologyException: Cannot do reasoning with inconsistent ontologies!
Reason for inconsistency: Literal value "https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.6.238"^^string does not belong to datatype anyURI
```

2023-09-15 09:22 UTC, mereolog commented on AboutIDMPDev.rdf
> +        <owl:imports rdf:resource="https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork/"/>
These two ontologies should be "registered" in AboutIDMPDev-ReferenceIndividuals.rdf as well because all and only ontologies "registered" there are subject to hygiene tests.

2023-09-15 11:36 UTC, tw-osthus commented on AboutIDMPDev.rdf
> +        <owl:imports rdf:resource="https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork/"/>
done

2023-09-15 11:36 UTC, tw-osthus commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +		</rdf:subClassOf>
done

2023-09-18 08:35 UTC, mereolog commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +				<owl:onProperty rdf:resource="https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork/cmns-col;isIncludedIn"/>
rdf:resource="&cmns-col;isIncludedIn"/>

2023-09-18 08:56 UTC, tw-osthus commented on ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork.rdf
> +				<owl:onProperty rdf:resource="https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/PublicHealthInformationNetwork/cmns-col;isIncludedIn"/>
fixed

2023-09-20 03:48 UTC, ElisaKendall submitted a review, later dismissed

2023-09-20 04:08 UTC, ElisaKendall approved these changes
Approved with the changes made.

2023-09-20 14:59 UTC, mereolog approved these changes

2023-09-20 14:59 UTC, merged