IDMP-643 add ISO 5128 representations of human sexes
edmcouncil/idmp pull request #452
Opened 2023-08-15 10:03 UTC by tw-osthus

Description:
defined concepts in MVF vocabulary and as ISO 21090 ConceptDescriptors for use in specifying target populations based on gender

ISO IDMP mentions ISO 5128 as reference, but it should be replaced by a better vocabulary

2023-09-07 07:19 UTC, mereolog requested changes
ERROR  09:18:32  An error occurred during reasoning: Cannot do reasoning with inconsistent ontologies!
Reason for inconsistency: Literal value "Female"@en does not belong to datatype string.
org.mindswap.pellet.exceptions.InconsistentOntologyException: Cannot do reasoning with inconsistent ontologies!
Reason for inconsistency: Literal value "Female"@en does not belong to datatype string

2023-09-07 12:04 UTC, tw-osthus commented
removed language tag to comply with datatype range

2023-09-23 01:02 UTC, ElisaKendall approved these changes
I approve this with the changes that have been made.

2023-09-23 06:12 UTC, ElisaKendall approved these changes

2023-09-25 05:26 UTC, mereolog approved these changes

2023-09-25 07:53 UTC, merged