IDMP-640 add characteristics for target populations
edmcouncil/idmp pull request #453
Opened 2023-08-15 10:18 UTC by tw-osthus

Description:
* add time unit
* add age characteristics
* add gender characteristics
* add race characteristics 
* add characteristics on physiological conditions

controlled vocabularies are added in IDMP-641 and IDMP-643

2023-10-06 09:55 UTC, tw-osthus commented
I had to remove the qlaira example rdf, because the RDF normalizer cannot handle it.

2023-10-06 13:49 UTC, mereolog requested changes

2023-10-06 13:49 UTC, mereolog commented on ISO/ISO11240-UnitsOfMeasurement.rdf
> +		<rdfs:subClassOf rdf:resource="&cmns-qtu;Quantity"/>
cmns-qtu:Quantity does not exist in cmns-qtu.

2023-10-06 13:49 UTC, mereolog commented on ISO/ISO11615-MedicinalProducts.rdf
> +		<rdfs:subClassOf rdf:resource="&cmns-qtu;Quantity"/>
cmns-qtu:Quantity does not exist in cmns-qtu.

2023-10-06 13:49 UTC, mereolog commented on ISO/ISO11240-UnitsOfMeasurement.rdf
> +		<rdfs:subClassOf rdf:resource="&cmns-qtu;QuantityValue"/>
cmns-qtu:QuantityValue does not exist in cmns-qtu.

2023-10-06 13:49 UTC, mereolog commented on ISO/ISO11240-UnitsOfMeasurement.rdf
> +		<rdfs:subClassOf rdf:resource="&cmns-qtu;QuantityValueRange"/>
cmns-qtu:QuantityValueRange does not exist in cmns-qtu.

2023-10-09 12:01 UTC, tw-osthus commented on ISO/ISO11240-UnitsOfMeasurement.rdf
> +		<rdfs:subClassOf rdf:resource="&cmns-qtu;QuantityValueRange"/>
fixed renamed classes

2023-10-09 12:01 UTC, tw-osthus commented on EXT/Examples/QlairaExample.rdf
blocks the build and commit

2023-10-09 12:02 UTC, tw-osthus commented on ISO/ISO11240-UnitsOfMeasurement.rdf
> +		<rdfs:subClassOf rdf:resource="&cmns-qtu;QuantityValue"/>
fixed renamed class

2023-10-12 12:20 UTC, mereolog commented
@tw-osthus would you mind resolving the merge conflict?

2023-10-23 08:30 UTC, mereolog requested changes

2023-10-23 08:30 UTC, mereolog commented on ISO/ISO11615-MedicinalProducts.rdf
> +		<skos:definition>classifier for ages</skos:definition>
"Age classifier is a classifier for ages." - this is almost a circular definition.

2023-10-23 08:30 UTC, mereolog commented on CMNS/DatesAndTimes.rdf
> +	</owl:Class>
Modeling maximum durations as classes, besides modeling them as object properties, looks odd. It like defining the maximum income - any income can be maximal if you set the appropriate context.
Also what does it mean that something is an upper bound of duration, which is defined as an interval? Suppose that something lasts 5 minutes, i.e., that a 5-minute interval is a duration. What does it mean that it has an upper bound?
I have the same doubts about minimal durations.

2023-10-23 08:30 UTC, mereolog commented on CMNS/DatesAndTimes.rdf
> +	</owl:Class>
Since a duration range is (provably) a duration, what does it mean that a duration range is range expressing bounds on durations? Since duration is an interval, what does it mean that some duration is a range of (another duration?)?

@tw-osthus can you add some examples - at least to this pull-request if not to the ontology?

![image](https://github.com/edmcouncil/idmp/assets/11171688/2ed46274-5f20-4626-9546-85f311c36594)

2023-10-23 09:11 UTC, tw-osthus commented on ISO/ISO11615-MedicinalProducts.rdf
> +		<skos:definition>classifier for ages</skos:definition>
no it is not, if both age and classifier are defined, which they are

2023-10-23 09:26 UTC, tw-osthus commented on CMNS/DatesAndTimes.rdf
> +	</owl:Class>
These are different kind of ranges. A duration is a range of time from one point in time to another point in time.
The duration range is a range of durations, e.g. from 10 min to 20 min. 10 min and 20  min are durations. The age characteristic is for example 18 to 60 years for adults or 1 to 2 weeks for newborn.

2023-10-23 13:23 UTC, mereolog commented on CMNS/DatesAndTimes.rdf
> +	</owl:Class>
> I assume duration is **information about** time, not time itself. This allows maximum time to be a subclass. If we define duration as the physical time, then we can't.

But then we should mark this assumption somewhere in the ontology because currently the definition of duration and their supertypes look like physical features.

2023-10-24 07:29 UTC, tw-osthus commented on CMNS/DatesAndTimes.rdf
> +	</owl:Class>
yes

2023-10-30 15:44 UTC, ElisaKendall commented
> @tw-osthus would you mind resolving the merge conflict?

Done

2023-10-30 17:10 UTC, ElisaKendall approved these changes
Approved with the changes I've made.

2023-10-31 16:24 UTC, avilesg submitted a review, later dismissed

2023-10-31 20:31 UTC, ElisaKendall approved these changes

2023-11-01 20:33 UTC, avilesg submitted a review, later dismissed

2023-11-01 20:51 UTC, ElisaKendall approved these changes

2023-11-01 20:52 UTC, avilesg approved these changes

2023-11-01 21:12 UTC, merged