IDMP-645 add SPAR ontologies and an extension
edmcouncil/idmp pull request #468
Opened 2023-09-13 09:30 UTC by tw-osthus

Description: SPAR ontologies added for describing deep links into documents together with an extension that allows to describe table elements and partial or rephrased text content. This is used to make references quoting text from documents with no embedded markup such as PDF, where the structure of the document must be described externally.

2023-11-09 04:00 UTC, ElisaKendall submitted a review, later dismissed
This is ok now with the changes that have been made. Note that the SPAR ontologies should be excluded from the hygiene testing due to the inclusion of SWRL rules whose IRIs do not conform with our policies unless the policies can be augmented to allow them. There are other anomalies in these ontologies that we will reach out to the authors to address if possible.

2023-11-09 10:08 UTC, mereolog requested changes

2023-11-09 10:08 UTC, mereolog commented on SPAR/doco.rdf
> +	<owl:Class rdf:about="http://www.essepuntato.it/2008/12/pattern#Pattern">
Pattern is equivalent to owl:Thing:

![image](https://github.com/edmcouncil/idmp/assets/11171688/762f574f-c3f0-453a-817e-b373c3acd54c)

2023-11-09 17:58 UTC, ElisaKendall commented on SPAR/MetadataSPAR.rdf
> +	<owl:NamedIndividual rdf:about="&spar-mod;SPARModule">
@merelog I created a new MetadataSPAR.rdf file in the SPAR folder to address this. Why does it also need to be in MetadataEXT?

2023-11-09 18:01 UTC, ElisaKendall commented on EXT/Extensions/DocumentComponents.rdf
> +<rdf:RDF xml:base="https://spec.pistoiaalliance.org/idmp/ontology/EXT/DocumentComponents/"
Done.

2023-11-09 18:03 UTC, ElisaKendall commented on SPAR/c4o.rdf
> +	<owl:Class rdf:about="http://purl.org/spar/c4o/SingleLocationPointerList">
@mereolog We are not using this one and it is not included in the metadata, etc. Other SPAR ontologies may import it, but I excluded it from testing because of this. We will write to the authors to see if they would be willing to accept our suggestions, but no promises on that.

2023-11-09 18:03 UTC, ElisaKendall commented on SPAR/datacite.rdf
> +		<owl:imports rdf:resource="http://purl.org/spar/literal"/>
@mereolog We are not using this one - see my comment above. We will write the authors and suggest eliminating dependencies that no longer exist.

2023-11-09 18:04 UTC, ElisaKendall commented on SPAR/doco.rdf
> +	<owl:Class rdf:about="http://www.essepuntato.it/2008/12/pattern#Pattern">
@mereolog Saw that too. Again, all we can do is write to the authors and see if they will address these things or if they would allow us to do so.

2023-11-09 19:41 UTC, avilesg submitted a review, later dismissed

2023-11-09 20:19 UTC, ElisaKendall approved these changes

2023-11-10 07:39 UTC, mereolog commented on SPAR/MetadataSPAR.rdf
> +	<owl:NamedIndividual rdf:about="&spar-mod;SPARModule">
> @merelog I created a new MetadataSPAR.rdf file in the SPAR folder to address this. Why does it also need to be in MetadataEXT?

You need to add spar-mod:SPARModule as part to [MetadataIDMP.rdf](https://github.com/edmcouncil/idmp/blob/master/MetadataIDMP.rdf) and not to MetadataEXT. See, for example,
https://github.com/edmcouncil/idmp/blob/ff67c2be310a3b8ceda3e7b61f2647e59f03e60f/MetadataIDMP.rdf#L60-L60.

That is, you need to add a line:
`<dct:hasPart rdf:resource="&spar-mod;SPARModule"/>`

2023-11-12 00:30 UTC, ElisaKendall commented on SPAR/MetadataSPAR.rdf
> +	<owl:NamedIndividual rdf:about="&spar-mod;SPARModule">
It's there.

2023-11-13 07:13 UTC, mereolog requested changes

2023-11-13 07:13 UTC, mereolog commented on EXT/Extensions/DocumentComponents.rdf
> +<rdf:RDF xml:base="https://spec.pistoiaalliance.org/idmp/ontology/EXT/DocumentComponents/"
This ontology has a wrong IRI.
Instead of
`https://spec.pistoiaalliance.org/idmp/ontology/EXT/DocumentComponents/`
we should have
`https://spec.pistoiaalliance.org/idmp/ontology/EXT/Extensions/DocumentComponents/`

Otherwise the resolution service and onto-viewer will not find it.

2023-11-13 16:33 UTC, ElisaKendall commented on EXT/Extensions/DocumentComponents.rdf
> +<rdf:RDF xml:base="https://spec.pistoiaalliance.org/idmp/ontology/EXT/DocumentComponents/"
Corrected.

2023-11-13 16:34 UTC, ElisaKendall approved these changes

2023-11-13 18:36 UTC, mereolog approved these changes

2023-11-13 21:10 UTC, merged