IDMP-632 - Batch should be a subclass of Constituent rather than Product
edmcouncil/idmp pull request #486
Opened 2023-09-25 16:17 UTC by ElisaKendall

Description: Revised the inheritance for Batch and Lot to subclass constituent rather than product

2023-09-26 07:39 UTC, tw-osthus commented
see my https://github.com/edmcouncil/idmp/issues/485

2023-09-26 07:42 UTC, tw-osthus requested changes
I am not sure. 
A product is matter that is being produced. A batch is a collection of things being produced at the same time. This makes batch a collection, not a constituent, and I do not see, why it is not a product. It is not necessarily a good, because the batch is not sold as such. A lot is something that is sold together as one item. Again more a collection than a constituent.

2023-09-26 15:10 UTC, ElisaKendall commented
> I am not sure. A product is matter that is being produced. A batch is a collection of things being produced at the same time. This makes batch a collection, not a constituent, and I do not see, why it is not a product. It is not necessarily a good, because the batch is not always sold as such. A lot is a collection of things that are sold together as one item, again not constituent.

@tw-osthus I'm not sure who raised this in one of our Monday meetings - it was one of the pharma companies I think. I've asked Johnson & Johnson how they represent it - we can confirm the approach on Monday next week before we finalize the release.

2023-09-29 06:38 UTC, mereolog approved these changes

2023-10-04 06:58 UTC, merged