IDMP-592 - Complete the modeling work required for Nucleic Acids (WIP)
edmcouncil/idmp pull request #488
Opened 2023-09-25 17:03 UTC by ElisaKendall

Description: 
1. Added metadata to nucleic acid substance, added nucleic acid sequence type per the ISO specification

2023-09-28 07:24 UTC, mereolog requested changes

2023-09-28 08:45 UTC, tw-osthus requested changes

2023-09-28 08:45 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +	<owl:ObjectProperty rdf:about="&idmp-sub;hasFivePrimeSubstanceName">
Why do we need "has related substance name"/"has reltated substance identifier" and their subproperties, when it is enough to have "has related substance/has substance name". If we want to refer from the nucleic acid to the sugar, a property "has sugar" as subclass of has related substance or has moiety make more sense to me. 
Referencing to related entities via ids or names is relational modeling, not graph based modeling.
The 3/5 prime and sugar are moieties or constituents of the nucleic acid.

2023-09-28 08:45 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +	<owl:DatatypeProperty rdf:about="&idmp-sub;hasLinkageConnectivity">
as this expects a code it should be an object property pointing to a controlled term. Then their is no need to encode the allowed values as "3’→5’, 3’→3’ or 5’→5’" which is human readable, but not machine readable.

2023-09-28 08:45 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +	<owl:DatatypeProperty rdf:about="&idmp-sub;hasResidueSite">
Again this should be an object property refering to a residue site, which is a locator in the structure. It is fine to start with a description of the locator, but if we have a machine readable encoding of residue site, we will have to define another distinct property "has residue site as object". This is not what we want, and we should keep the pattern using property paths for such cases, when we can expect a machine readable way of exactly specifying the location.

2023-09-28 14:01 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +	</owl:DatatypeProperty>
@merelog Done

2023-09-28 14:03 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +	<owl:ObjectProperty rdf:about="&idmp-sub;hasFivePrimeSubstanceName">
@tw-osthus I thought about that, but there are specific queries that may be easier with explicit properties, and the standard requires it. Thus, we've used property chains, to connect through the substance to its name or identifier here.

2023-09-28 14:04 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +	<owl:DatatypeProperty rdf:about="&idmp-sub;hasLinkageConnectivity">
@tw-osthus I did not find controlled vocabularies for this, but didn't search SPOR. The standard indicates that it is a string value, for this property.

2023-09-28 14:10 UTC, ElisaKendall commented on ISO/ISO11238-Substances.rdf
> +	<owl:DatatypeProperty rdf:about="&idmp-sub;hasResidueSite">
@tw-osthus The goal this round was to represent what is in the standard. I'd like to defer these changes to review work once we have the initial approach done, and then refine this based on understanding the approach that the SMEs want to take and whether or not there are controlled vocabularies for this. Again, I didn't search, but think we should review with SMEs before making this change.

2023-09-28 16:47 UTC, avilesg approved these changes

2023-09-29 06:33 UTC, mereolog approved these changes

2023-09-29 15:10 UTC, merged