IDMP-594 - Complete the definition of protein substances (WIP)
edmcouncil/idmp pull request #504
Opened 2023-10-11 17:55 UTC by ElisaKendall

Description:
1. initial set of additions / revisions to augment the definition of protein substance

2023-10-12 12:37 UTC, tw-osthus requested changes
we should define C-Terminal modification and N-Terminal modification classes as subclass of modfication method and link the subunit to these by hasCTerminalModification, resp. hasNTerminalModification. The double link by identifier and name is relational modeling and might easily become inconsistent, as nothing ensures that modification id and name point to the same modification.

2023-10-12 15:12 UTC, ElisaKendall commented
> we should define C-Terminal modification and N-Terminal modification classes as subclass of modfication method and link the subunit to these by hasCTerminalModification, resp. hasNTerminalModification. The double link by identifier and name is relational modeling and might easily become inconsistent, as nothing ensures that modification id and name point to the same modification.

Ok - I wondered about that. This isn't the only case where these kinds of pattens occur, where there is a pointer to a related substance identifier and name, in other words. I'll look into using property chains to chain through to the identifier and name as an alternative to facilitate queries.

2023-10-13 09:25 UTC, mereolog approved these changes

2023-10-13 09:25 UTC, mereolog commented on ISO/ISO11238-Substances.rdf
> +		<rdfs:range rdf:resource="&xsd;integer"/>
Perhaps xsd:nonNegativeInteger would be more appropriate here.
This comment applies also to other subproperties of hasIntegerValue.

2023-10-13 11:15 UTC, tw-osthus approved these changes

2023-10-13 13:28 UTC, merged