IDMP-673 - Complete the minimal set of required fields from Annex L for Polymers (WIP)
edmcouncil/idmp pull request #509
Opened 2023-10-25 01:51 UTC by ElisaKendall

Description: 
1. initial build out of the polymer substance class with some of its defining elements

2023-10-26 13:03 UTC, tw-osthus requested changes

2023-10-26 13:03 UTC, tw-osthus commented on ISO/ISO11238-Substances.rdf
> +		<skos:definition>classifier specifying the specify and quantify the monomers used for the synthesis of the polymer or copolymer</skos:definition>
typo?

2023-10-26 15:20 UTC, tw-osthus approved these changes

2023-10-27 19:29 UTC, avilesg approved these changes

2023-10-27 19:29 UTC, merged