Fixed URLs
edmcouncil/idmp pull request #529
Opened 2023-11-13 08:17 UTC by konradkrebs1411

2023-11-13 09:03 UTC, aliariff commented on etc/transformation/SPOR/substances/spor-substances.rqg
> +    IF(?Substance_Type = "Structurally Diverse - Allergen", spor-st:200000005026,https://pistoiaalliance.accurids.com/search
what is this change?

2023-11-13 09:07 UTC, konradkrebs1411 commented on etc/transformation/SPOR/substances/spor-substances.rqg
> +    IF(?Substance_Type = "Structurally Diverse - Allergen", spor-st:200000005026,https://pistoiaalliance.accurids.com/search
I cannot tell you, but I removed this weird link

2023-11-13 09:07 UTC, aliariff approved these changes

2023-11-16 10:56 UTC, mereolog requested changes

2023-11-16 10:56 UTC, mereolog commented on etc/transformation/SPOR/substances/spor-substances.rqg
> +    IF(?Name_Source = "USP", idmp-amra:USPharmacopeiaMedicinesCompendium, # valid
idmp-amra is a wrong prefix - it should read idmp-nara - see: https://github.com/edmcouncil/idmp/blob/a73945606fbbda3ee093b36e4132226a746c04bf/ISO/NorthAmericanJurisdiction/NorthAmericanRegistrationAuthorities.rdf#L17

2023-11-16 10:56 UTC, mereolog commented on etc/transformation/SPOR/substances/spor-substances.rqg
>  PREFIX idmp-amra: <https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/NorthAmericanRegistrationAuthorities/>
idmp-amra is a wrong prefix - see the other comment.

2023-11-16 10:56 UTC, mereolog commented on etc/transformation/GSRS/gsrs-public-data-relationships.rqg
> +PREFIX idmp-nara: <https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/NorthAmericanRegulatoryAgencies>
This is a wrong prefix - it should read idmp-narga - see: https://github.com/edmcouncil/idmp/blob/a73945606fbbda3ee093b36e4132226a746c04bf/ISO/NorthAmericanJurisdiction/NorthAmericanRegulatoryAgencies.rdf#L12

2023-11-16 10:56 UTC, mereolog commented on etc/transformation/GSRS/gsrs-public-data-relationships.rqg
> +    IF(str(?RelationshipType) = "ACTIVE MOIETY", idmp-nara:RegulatoryContext-FoodAndDrugAdministrationGeneral,
This is a wrong prefix - see the other comment.

2023-11-16 10:56 UTC, mereolog commented on etc/transformation/GSRS/gsrs-public-data-relationships.rqg
> +    IF(str(?RelationshipType) = "ACTIVE MOIETY (FOR EXCLUSIVITY)", idmp-nara:RegulatoryContext-ActiveMoietyForFoodAndDrugAdministrationExclusivity,
This is a wrong prefix - see the other comment.

2023-11-16 10:56 UTC, mereolog commented on etc/transformation/GSRS/gsrs-public-data-relationships.rqg
>  PREFIX idmp-amra: <https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/NorthAmericanRegistrationAuthorities/>
idmp-amra is a wrong prefix - see the other comment.

2023-11-16 15:38 UTC, mereolog requested changes

2023-11-16 15:38 UTC, mereolog commented on etc/transformation/GSRS/gsrs-public-data-relationships.rqg
> +PREFIX idmp-narga: <https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/NorthAmericanRegulatoryAgencies>
Instead of:
`<https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/NorthAmericanRegulatoryAgencies>`
there should be:
`<https://spec.pistoiaalliance.org/idmp/ontology/ISO/NorthAmericanJurisdiction/NorthAmericanRegulatoryAgencies/>`
So the '/' at the end.

2023-11-17 10:13 UTC, mereolog approved these changes

2023-11-17 10:25 UTC, aliariff approved these changes

2023-11-17 10:52 UTC, merged