Add and modify catalog files in subfolders
edmcouncil/idmp pull request #539
Opened 2023-12-01 15:50 UTC by mereolog

This pull request amends catalog files in IDMP subfolders.
It fixes #507 .

2023-12-04 08:24 UTC, tw-osthus requested changes

2023-12-04 08:24 UTC, tw-osthus commented on LCC/Countries/Regions/catalog-v001.xml
> +        <uri id="Automatically generated entry, Timestamp=1701443767275" name="https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-GB/" uri="ISO3166-2-SubdivisionCodes-GB.rdf"/>
id should be UUID

2023-12-06 16:30 UTC, ElisaKendall commented on LCC/Countries/Regions/catalog-v001.xml
> +        <uri id="Automatically generated entry, Timestamp=1701443767275" name="https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-GB/" uri="ISO3166-2-SubdivisionCodes-GB.rdf"/>
@mereolog @tw-osthus Do we really need all of these sub-catalogs? I did not create them originally unless we needed them for testing purposes?

2023-12-07 07:57 UTC, mereolog commented on LCC/Countries/Regions/catalog-v001.xml
> +        <uri id="Automatically generated entry, Timestamp=1701443767275" name="https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-GB/" uri="ISO3166-2-SubdivisionCodes-GB.rdf"/>
> @mereolog @tw-osthus Do we really need all of these sub-catalogs? I did not create them originally unless we needed them for testing purposes?

Sometimes, I want to open a single ontology from a subfolder in Protege, and most often, Protege complains about missing imports. This pull request is to mitigate against this. It also addresses #507, which raises the same point.

2023-12-07 13:14 UTC, tw-osthus approved these changes

2023-12-07 13:17 UTC, merged