IDMP-713 - Augment the ontology to incorporate additional information related to biologics (WIP)
edmcouncil/idmp pull request #554
Opened 2024-02-08 18:17 UTC by ElisaKendall

1. Augmented the definition of organism to include organism name and identifier
2. Added property chains to enable connections between source material and the name and identifier of an organism

2024-02-28 21:34 UTC, tw-osthus requested changes
xml:lang is invalid, everything else is good

2024-02-28 21:34 UTC, tw-osthus commented on CMNS/Organizations.rdf
> +		<rdfs:label xml:lang="gb">organisation</rdfs:label>
this should be xml:lang="en-GB" instead of "gb"

2024-02-28 21:42 UTC, ElisaKendall commented
> xml:lang is invalid, everything else is good

Fixed

2024-02-28 21:52 UTC, tw-osthus approved these changes

2024-02-29 09:26 UTC, konradkrebs1411 approved these changes

2024-02-29 18:07 UTC, merged