Few ShACL examples added for discussion (WIP)
edmcouncil/idmp pull request #563
Opened 2024-04-08 12:53 UTC by mereolog

This is to add a couple of SHACL examples for the sake of discussion

2024-04-17 18:09 UTC, tw-osthus requested changes

2024-04-17 18:09 UTC, tw-osthus commented on etc/shacl/substance_shacl_human.shacl
> +			sh:or (
this looks wrong to me: sh:or should have shapes instead of classes in the list

2024-04-18 12:23 UTC, mereolog commented on etc/shacl/substance_shacl_human.shacl
> +			sh:or (
Fixed, I hope

2024-04-29 10:21 UTC, Heiner-Oberkampf approved these changes
Great initial example to test usage for quality and display of information

2024-04-29 10:21 UTC, merged