IDMP-747 - Complete the ISO 11615 details related to marketing authorization (WIP)
edmcouncil/idmp pull request #614
Opened 2024-07-17 14:47 UTC by ElisaKendall

Description:

1. Completed attributes for marketing authorization procedure and marketing application

2024-07-25 07:29 UTC, tw-osthus requested changes
adding skos:prefLabel is not a solution for the problem. It expects still a langstring. If skos:prefLabel "authorisation"@en-GB or another translation is added we will have the issue again. The problem is in the unit test evaluation. We can have multiple labels so any test for labels is brittle. My solution in AFO was to move all non-US-English labels into a language specific add-on ontology, so that skos:prefLabel was unique. 
Filtering for lang=en-US in sparql is possible but makes the queries more complicated.

As for now, I am willing to approve this, but it is for me a hack not a solution.

2024-07-25 17:46 UTC, avilesg approved these changes

2024-07-25 18:14 UTC, avilesg reviewed
After reading comments on this merge request, I had a few iterations with chatgpt to document the following:

### Background and Problem Summary

In managing ontologies, particularly in international contexts, it's common to use language tags to indicate the language of string literals. For example, the triple `<subject> rdfs:label "authorisation"@en-GB` indicates that the label "authorisation" is in British English. However, this can create inconsistencies and challenges in maintaining the ontology, especially if different language tags are used indiscriminately within the core ontology.

### Problem

1. **Inconsistency**: The use of different language tags for labels within the core ontology can lead to inconsistencies and make it difficult to maintain a unified structure.
2. **Testing Difficulties**: Unit tests expecting specific language tags can fail if language attributions are not standardized.
3. **Maintenance Complexity**: Managing labels with multiple language tags in a single ontology file increases the complexity of updates and maintenance.

### Proposed Path Forward

To address these issues, we propose the following approach:

1. **Conventions for Language Tags**:
   - Use `skos:prefLabel` for primary labels without any language tags, implicitly considering them as `@en-US`.
   - Use `rdfs:label` or other appropriate properties with language tags for language-specific labels.
   - Separate language-specific labels into distinct language-specific graphs or files.

2. **Migration Process**:
   - **Analyze Existing Ontologies**: Identify and extract all triples with language tags to understand the scope and diversity of languages used.
   - **Separate Triples by Language**: Organize and separate triples with language tags into distinct graphs or files based on their language.
   - **Maintain Language Add-ons**: Implement a structured approach for managing these separate language graphs using version control and clear documentation.

3. **Implementation and Automation**:
   - Provide scripts to facilitate the extraction and separation of language-tagged triples.
   - Use pre-commit hooks in Git to enforce the new conventions and prevent the addition of language tags to the core ontology.

### Detailed Steps and Code Implementation

#### Conventions for Using Language Tags

1. **Primary Label Convention**:
   - `skos:prefLabel` should be used for primary labels without any language attribution, implicitly considered `@en-US`.

2. **Language-Specific Labels**:
   - Use `rdfs:label` with appropriate language tags (`@en-GB`, `@fr`, etc.) for language-specific labels.

3. **Language Add-ons**:
   - Maintain separate files or graphs for each language to keep the primary ontology clean and consistent.

#### Migration Process

1. **Extract and Analyze Language Tags**:

```python
from rdflib import Graph, Literal

def extract_language_tags(graph: Graph):
    languages = set()
    for _, _, o in graph:
        if isinstance(o, Literal) and o.language:
            languages.add(o.language)
    return languages

# Load your ontology graph
g = Graph()
g.parse("your-ontology-file.ttl", format="turtle")

# Extract language tags
languages = extract_language_tags(g)
print(f"Languages used in the ontology: {languages}")
```

2. **Separate Triples by Language**:

```python
def separate_triples_by_language(graph: Graph, languages: set):
    language_graphs = {lang: Graph() for lang in languages}
    
    for s, p, o in graph:
        if isinstance(o, Literal) and o.language:
            language_graphs[o.language].add((s, p, o))
    
    return language_graphs

# Separate the triples
language_graphs = separate_triples_by_language(g, languages)

# Save each language graph to a separate file
for lang, lang_graph in language_graphs.items():
    lang_graph.serialize(f"ontology_{lang}.ttl", format="turtle")
```

3. **Maintain Separate Language Add-ons**:
   - Use version control (e.g., Git) to manage the separate language graphs.
   - Document the structure, conventions, and guidelines for maintaining these language-specific files.

#### Pre-Commit Hook to Enforce Conventions

Create a `pre-commit` hook script to ensure new commits do not add language tags to the core ontology:

```bash
#!/bin/bash

# Temporary file to hold the diff
tempfile=$(mktemp)

# Get the diff of the changes to be committed
git diff --cached > "$tempfile"

# Function to check for language tags in core ontology
check_for_language_tags() {
    if grep -E '@[a-zA-Z]{2}(-[a-zA-Z]{2})?' "$tempfile"; then
        echo "Error: Language tags found in the core ontology."
        echo "Please move language-specific labels to their respective language files."
        rm "$tempfile"
        exit 1
    fi
}

# List of files to check
files_to_check=("core-ontology.ttl")

# Check each file for language tags
for file in "${files_to_check[@]}"; do
    if grep -q "$file" "$tempfile"; then
        check_for_language_tags
    fi
done

# Cleanup
rm "$tempfile"
exit 0
```

Make the script executable:

```bash
chmod +x .git/hooks/pre-commit
```

### Conclusion

By following this approach, you can achieve a consistent and maintainable structure for your ontologies, separate language-specific labels into appropriate files, and enforce these conventions using automated tools and version control practices. This will simplify the maintenance of your ontologies and ensure clarity and consistency across different language representations.

2024-07-26 06:57 UTC, mereolog commented
> @mereolog - what would we need to do with the tests to address this?

There are various options - two/three were suggested by @tw-osthus:
1. Leave the PR as it is now
2. Filter out the results to the specific language tag
3. Move all non-default langliterals to a different file.

To this I would add:
4. Change the expected results so that they fit the actual results - it is a kind of a hack though
5. Send to ?ProductRoleType not a literal (rdfs:label, skos:prefLabel, etc.) but the actual IRI, e.g., either idmp-mprd:AuthorizedMedicinalProduct or idmp-mprd:InvestigationalMedicinalProduct.

I would vote for 5 since this decreases the dependency of the cq on the label situation in the ontology. Also it requires a considerably small change, although both the query and the expected results will need be changed.

2024-07-26 13:49 UTC, tw-osthus approved these changes

2024-07-26 14:14 UTC, mereolog approved these changes

2024-07-27 14:01 UTC, avilesg approved these changes

2024-07-27 14:01 UTC, merged